// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"time"

	"github.com/ryuyb/fusion/internal/core/command"
	"github.com/ryuyb/fusion/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Login(ctx context.Context, cmd command.LoginCommand) (string, time.Time, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.LoginCommand) (string, time.Time, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.LoginCommand) string); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, command.LoginCommand) time.Time); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, command.LoginCommand) error); ok {
		r2 = returnFunc(ctx, cmd)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockAuthService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd command.LoginCommand
func (_e *MockAuthService_Expecter) Login(ctx interface{}, cmd interface{}) *MockAuthService_Login_Call {
	return &MockAuthService_Login_Call{Call: _e.mock.On("Login", ctx, cmd)}
}

func (_c *MockAuthService_Login_Call) Run(run func(ctx context.Context, cmd command.LoginCommand)) *MockAuthService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.LoginCommand
		if args[1] != nil {
			arg1 = args[1].(command.LoginCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Login_Call) Return(s string, time1 time.Time, err error) *MockAuthService_Login_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *MockAuthService_Login_Call) RunAndReturn(run func(ctx context.Context, cmd command.LoginCommand) (string, time.Time, error)) *MockAuthService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthService
func (_mock *MockAuthService) Register(ctx context.Context, cmd command.RegisterCommand) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, command.RegisterCommand) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd command.RegisterCommand
func (_e *MockAuthService_Expecter) Register(ctx interface{}, cmd interface{}) *MockAuthService_Register_Call {
	return &MockAuthService_Register_Call{Call: _e.mock.On("Register", ctx, cmd)}
}

func (_c *MockAuthService_Register_Call) Run(run func(ctx context.Context, cmd command.RegisterCommand)) *MockAuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 command.RegisterCommand
		if args[1] != nil {
			arg1 = args[1].(command.RegisterCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_Register_Call) Return(err error) *MockAuthService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_Register_Call) RunAndReturn(run func(ctx context.Context, cmd command.RegisterCommand) error) *MockAuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserService
func (_mock *MockUserService) Create(ctx context.Context, cmd *command.CreateUserCommand) (*domain.User, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *command.CreateUserCommand) (*domain.User, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *command.CreateUserCommand) *domain.User); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *command.CreateUserCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *command.CreateUserCommand
func (_e *MockUserService_Expecter) Create(ctx interface{}, cmd interface{}) *MockUserService_Create_Call {
	return &MockUserService_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *MockUserService_Create_Call) Run(run func(ctx context.Context, cmd *command.CreateUserCommand)) *MockUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *command.CreateUserCommand
		if args[1] != nil {
			arg1 = args[1].(*command.CreateUserCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Create_Call) Return(user *domain.User, err error) *MockUserService_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_Create_Call) RunAndReturn(run func(ctx context.Context, cmd *command.CreateUserCommand) (*domain.User, error)) *MockUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserService
func (_mock *MockUserService) Delete(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserService_Expecter) Delete(ctx interface{}, id interface{}) *MockUserService_Delete_Call {
	return &MockUserService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserService_Delete_Call) Run(run func(ctx context.Context, id int64)) *MockUserService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Delete_Call) Return(err error) *MockUserService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_Delete_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockUserService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type MockUserService
func (_mock *MockUserService) FindById(ctx context.Context, id int64) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type MockUserService_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockUserService_Expecter) FindById(ctx interface{}, id interface{}) *MockUserService_FindById_Call {
	return &MockUserService_FindById_Call{Call: _e.mock.On("FindById", ctx, id)}
}

func (_c *MockUserService_FindById_Call) Run(run func(ctx context.Context, id int64)) *MockUserService_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_FindById_Call) Return(user *domain.User, err error) *MockUserService_FindById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_FindById_Call) RunAndReturn(run func(ctx context.Context, id int64) (*domain.User, error)) *MockUserService_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserService
func (_mock *MockUserService) List(ctx context.Context, page int, pageSize int) ([]*domain.User, int, error) {
	ret := _mock.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.User
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.User, int, error)); ok {
		return returnFunc(ctx, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*domain.User); ok {
		r0 = returnFunc(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = returnFunc(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockUserService_Expecter) List(ctx interface{}, page interface{}, pageSize interface{}) *MockUserService_List_Call {
	return &MockUserService_List_Call{Call: _e.mock.On("List", ctx, page, pageSize)}
}

func (_c *MockUserService_List_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockUserService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserService_List_Call) Return(users []*domain.User, n int, err error) *MockUserService_List_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *MockUserService_List_Call) RunAndReturn(run func(ctx context.Context, page int, pageSize int) ([]*domain.User, int, error)) *MockUserService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserService
func (_mock *MockUserService) Update(ctx context.Context, cmd *command.UpdateUserCommand) (*domain.User, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *command.UpdateUserCommand) (*domain.User, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *command.UpdateUserCommand) *domain.User); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *command.UpdateUserCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *command.UpdateUserCommand
func (_e *MockUserService_Expecter) Update(ctx interface{}, cmd interface{}) *MockUserService_Update_Call {
	return &MockUserService_Update_Call{Call: _e.mock.On("Update", ctx, cmd)}
}

func (_c *MockUserService_Update_Call) Run(run func(ctx context.Context, cmd *command.UpdateUserCommand)) *MockUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *command.UpdateUserCommand
		if args[1] != nil {
			arg1 = args[1].(*command.UpdateUserCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Update_Call) Return(user *domain.User, err error) *MockUserService_Update_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_Update_Call) RunAndReturn(run func(ctx context.Context, cmd *command.UpdateUserCommand) (*domain.User, error)) *MockUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}
