// Code generated by ent, DO NOT EDIT.

package userfollowedstreamer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldUserID, v))
}

// StreamerID applies equality check predicate on the "streamer_id" field. It's identical to StreamerIDEQ.
func StreamerID(v int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldStreamerID, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldAlias, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldNotes, v))
}

// NotificationsEnabled applies equality check predicate on the "notifications_enabled" field. It's identical to NotificationsEnabledEQ.
func NotificationsEnabled(v bool) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldNotificationsEnabled, v))
}

// LastNotificationSentAt applies equality check predicate on the "last_notification_sent_at" field. It's identical to LastNotificationSentAtEQ.
func LastNotificationSentAt(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldLastNotificationSentAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldUserID, vs...))
}

// StreamerIDEQ applies the EQ predicate on the "streamer_id" field.
func StreamerIDEQ(v int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldStreamerID, v))
}

// StreamerIDNEQ applies the NEQ predicate on the "streamer_id" field.
func StreamerIDNEQ(v int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldStreamerID, v))
}

// StreamerIDIn applies the In predicate on the "streamer_id" field.
func StreamerIDIn(vs ...int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldStreamerID, vs...))
}

// StreamerIDNotIn applies the NotIn predicate on the "streamer_id" field.
func StreamerIDNotIn(vs ...int64) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldStreamerID, vs...))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasIsNil applies the IsNil predicate on the "alias" field.
func AliasIsNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIsNull(FieldAlias))
}

// AliasNotNil applies the NotNil predicate on the "alias" field.
func AliasNotNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotNull(FieldAlias))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldContainsFold(FieldAlias, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldContainsFold(FieldNotes, v))
}

// NotificationsEnabledEQ applies the EQ predicate on the "notifications_enabled" field.
func NotificationsEnabledEQ(v bool) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldNotificationsEnabled, v))
}

// NotificationsEnabledNEQ applies the NEQ predicate on the "notifications_enabled" field.
func NotificationsEnabledNEQ(v bool) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldNotificationsEnabled, v))
}

// NotificationChannelIdsIsNil applies the IsNil predicate on the "notification_channel_ids" field.
func NotificationChannelIdsIsNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIsNull(FieldNotificationChannelIds))
}

// NotificationChannelIdsNotNil applies the NotNil predicate on the "notification_channel_ids" field.
func NotificationChannelIdsNotNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotNull(FieldNotificationChannelIds))
}

// LastNotificationSentAtEQ applies the EQ predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtEQ(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldLastNotificationSentAt, v))
}

// LastNotificationSentAtNEQ applies the NEQ predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtNEQ(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldLastNotificationSentAt, v))
}

// LastNotificationSentAtIn applies the In predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtIn(vs ...time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldLastNotificationSentAt, vs...))
}

// LastNotificationSentAtNotIn applies the NotIn predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtNotIn(vs ...time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldLastNotificationSentAt, vs...))
}

// LastNotificationSentAtGT applies the GT predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtGT(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGT(FieldLastNotificationSentAt, v))
}

// LastNotificationSentAtGTE applies the GTE predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtGTE(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGTE(FieldLastNotificationSentAt, v))
}

// LastNotificationSentAtLT applies the LT predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtLT(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLT(FieldLastNotificationSentAt, v))
}

// LastNotificationSentAtLTE applies the LTE predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtLTE(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLTE(FieldLastNotificationSentAt, v))
}

// LastNotificationSentAtIsNil applies the IsNil predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtIsNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIsNull(FieldLastNotificationSentAt))
}

// LastNotificationSentAtNotNil applies the NotNil predicate on the "last_notification_sent_at" field.
func LastNotificationSentAtNotNil() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotNull(FieldLastNotificationSentAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasStreamer applies the HasEdge predicate on the "streamer" edge.
func HasStreamer() predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StreamerTable, StreamerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStreamerWith applies the HasEdge predicate on the "streamer" edge with a given conditions (other predicates).
func HasStreamerWith(preds ...predicate.Streamer) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(func(s *sql.Selector) {
		step := newStreamerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserFollowedStreamer) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserFollowedStreamer) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserFollowedStreamer) predicate.UserFollowedStreamer {
	return predicate.UserFollowedStreamer(sql.NotPredicates(p))
}
