// Code generated by ent, DO NOT EDIT.

package notificationchannel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldUserID, v))
}

// ChannelType applies equality check predicate on the "channel_type" field. It's identical to ChannelTypeEQ.
func ChannelType(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldChannelType, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldName, v))
}

// Enable applies equality check predicate on the "enable" field. It's identical to EnableEQ.
func Enable(v bool) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldEnable, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldPriority, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotIn(FieldUserID, vs...))
}

// ChannelTypeEQ applies the EQ predicate on the "channel_type" field.
func ChannelTypeEQ(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldChannelType, v))
}

// ChannelTypeNEQ applies the NEQ predicate on the "channel_type" field.
func ChannelTypeNEQ(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldChannelType, v))
}

// ChannelTypeIn applies the In predicate on the "channel_type" field.
func ChannelTypeIn(vs ...string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIn(FieldChannelType, vs...))
}

// ChannelTypeNotIn applies the NotIn predicate on the "channel_type" field.
func ChannelTypeNotIn(vs ...string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotIn(FieldChannelType, vs...))
}

// ChannelTypeGT applies the GT predicate on the "channel_type" field.
func ChannelTypeGT(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGT(FieldChannelType, v))
}

// ChannelTypeGTE applies the GTE predicate on the "channel_type" field.
func ChannelTypeGTE(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGTE(FieldChannelType, v))
}

// ChannelTypeLT applies the LT predicate on the "channel_type" field.
func ChannelTypeLT(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLT(FieldChannelType, v))
}

// ChannelTypeLTE applies the LTE predicate on the "channel_type" field.
func ChannelTypeLTE(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLTE(FieldChannelType, v))
}

// ChannelTypeContains applies the Contains predicate on the "channel_type" field.
func ChannelTypeContains(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldContains(FieldChannelType, v))
}

// ChannelTypeHasPrefix applies the HasPrefix predicate on the "channel_type" field.
func ChannelTypeHasPrefix(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldHasPrefix(FieldChannelType, v))
}

// ChannelTypeHasSuffix applies the HasSuffix predicate on the "channel_type" field.
func ChannelTypeHasSuffix(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldHasSuffix(FieldChannelType, v))
}

// ChannelTypeEqualFold applies the EqualFold predicate on the "channel_type" field.
func ChannelTypeEqualFold(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEqualFold(FieldChannelType, v))
}

// ChannelTypeContainsFold applies the ContainsFold predicate on the "channel_type" field.
func ChannelTypeContainsFold(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldContainsFold(FieldChannelType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldContainsFold(FieldName, v))
}

// ConfigIsNil applies the IsNil predicate on the "config" field.
func ConfigIsNil() predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIsNull(FieldConfig))
}

// ConfigNotNil applies the NotNil predicate on the "config" field.
func ConfigNotNil() predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotNull(FieldConfig))
}

// EnableEQ applies the EQ predicate on the "enable" field.
func EnableEQ(v bool) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldEnable, v))
}

// EnableNEQ applies the NEQ predicate on the "enable" field.
func EnableNEQ(v bool) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldEnable, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLTE(FieldPriority, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.NotificationChannel {
	return predicate.NotificationChannel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.NotificationChannel {
	return predicate.NotificationChannel(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.NotificationChannel) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.NotificationChannel) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.NotificationChannel) predicate.NotificationChannel {
	return predicate.NotificationChannel(sql.NotPredicates(p))
}
