// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/notificationchannel"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/predicate"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/user"
)

// NotificationChannelUpdate is the builder for updating NotificationChannel entities.
type NotificationChannelUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdate) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationChannelUpdate) SetUserID(v int64) *NotificationChannelUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableUserID(v *int64) *NotificationChannelUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChannelType sets the "channel_type" field.
func (_u *NotificationChannelUpdate) SetChannelType(v string) *NotificationChannelUpdate {
	_u.mutation.SetChannelType(v)
	return _u
}

// SetNillableChannelType sets the "channel_type" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableChannelType(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetChannelType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdate) SetName(v string) *NotificationChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableName(v *string) *NotificationChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotificationChannelUpdate) SetConfig(v map[string]interface{}) *NotificationChannelUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *NotificationChannelUpdate) ClearConfig() *NotificationChannelUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetEnable sets the "enable" field.
func (_u *NotificationChannelUpdate) SetEnable(v bool) *NotificationChannelUpdate {
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillableEnable(v *bool) *NotificationChannelUpdate {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *NotificationChannelUpdate) SetPriority(v int) *NotificationChannelUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *NotificationChannelUpdate) SetNillablePriority(v *int) *NotificationChannelUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *NotificationChannelUpdate) AddPriority(v int) *NotificationChannelUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelUpdate) SetUpdatedAt(v time.Time) *NotificationChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotificationChannelUpdate) SetUser(v *User) *NotificationChannelUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdate) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotificationChannelUpdate) ClearUser() *NotificationChannelUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := notificationchannel.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelType(); ok {
		if err := notificationchannel.ChannelTypeValidator(v); err != nil {
			return &ValidationError{Name: "channel_type", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.channel_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationChannel.user"`)
	}
	return nil
}

func (_u *NotificationChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelType(); ok {
		_spec.SetField(notificationchannel.FieldChannelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notificationchannel.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(notificationchannel.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(notificationchannel.FieldEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(notificationchannel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(notificationchannel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationchannel.UserTable,
			Columns: []string{notificationchannel.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationchannel.UserTable,
			Columns: []string{notificationchannel.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationChannelUpdateOne is the builder for updating a single NotificationChannel entity.
type NotificationChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationChannelMutation
}

// SetUserID sets the "user_id" field.
func (_u *NotificationChannelUpdateOne) SetUserID(v int64) *NotificationChannelUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableUserID(v *int64) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetChannelType sets the "channel_type" field.
func (_u *NotificationChannelUpdateOne) SetChannelType(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetChannelType(v)
	return _u
}

// SetNillableChannelType sets the "channel_type" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableChannelType(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetChannelType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *NotificationChannelUpdateOne) SetName(v string) *NotificationChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableName(v *string) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotificationChannelUpdateOne) SetConfig(v map[string]interface{}) *NotificationChannelUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *NotificationChannelUpdateOne) ClearConfig() *NotificationChannelUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetEnable sets the "enable" field.
func (_u *NotificationChannelUpdateOne) SetEnable(v bool) *NotificationChannelUpdateOne {
	_u.mutation.SetEnable(v)
	return _u
}

// SetNillableEnable sets the "enable" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillableEnable(v *bool) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetEnable(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *NotificationChannelUpdateOne) SetPriority(v int) *NotificationChannelUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *NotificationChannelUpdateOne) SetNillablePriority(v *int) *NotificationChannelUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *NotificationChannelUpdateOne) AddPriority(v int) *NotificationChannelUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotificationChannelUpdateOne) SetUpdatedAt(v time.Time) *NotificationChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *NotificationChannelUpdateOne) SetUser(v *User) *NotificationChannelUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (_u *NotificationChannelUpdateOne) Mutation() *NotificationChannelMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *NotificationChannelUpdateOne) ClearUser() *NotificationChannelUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the NotificationChannelUpdate builder.
func (_u *NotificationChannelUpdateOne) Where(ps ...predicate.NotificationChannel) *NotificationChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationChannelUpdateOne) Select(field string, fields ...string) *NotificationChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotificationChannel entity.
func (_u *NotificationChannelUpdateOne) Save(ctx context.Context) (*NotificationChannel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) SaveX(ctx context.Context) *NotificationChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotificationChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notificationchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationChannelUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := notificationchannel.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelType(); ok {
		if err := notificationchannel.ChannelTypeValidator(v); err != nil {
			return &ValidationError{Name: "channel_type", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.channel_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := notificationchannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.name": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "NotificationChannel.user"`)
	}
	return nil
}

func (_u *NotificationChannelUpdateOne) sqlSave(ctx context.Context) (_node *NotificationChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notificationchannel.Table, notificationchannel.Columns, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotificationChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notificationchannel.FieldID)
		for _, f := range fields {
			if !notificationchannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notificationchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ChannelType(); ok {
		_spec.SetField(notificationchannel.FieldChannelType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notificationchannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notificationchannel.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(notificationchannel.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Enable(); ok {
		_spec.SetField(notificationchannel.FieldEnable, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(notificationchannel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(notificationchannel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notificationchannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationchannel.UserTable,
			Columns: []string{notificationchannel.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationchannel.UserTable,
			Columns: []string{notificationchannel.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NotificationChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notificationchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
