// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/platform"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
)

// PlatformCreate is the builder for creating a Platform entity.
type PlatformCreate struct {
	config
	mutation *PlatformMutation
	hooks    []Hook
}

// SetDeleteAt sets the "delete_at" field.
func (_c *PlatformCreate) SetDeleteAt(v time.Time) *PlatformCreate {
	_c.mutation.SetDeleteAt(v)
	return _c
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (_c *PlatformCreate) SetNillableDeleteAt(v *time.Time) *PlatformCreate {
	if v != nil {
		_c.SetDeleteAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PlatformCreate) SetName(v string) *PlatformCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPlatformType sets the "platform_type" field.
func (_c *PlatformCreate) SetPlatformType(v platform.PlatformType) *PlatformCreate {
	_c.mutation.SetPlatformType(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *PlatformCreate) SetConfig(v map[string]interface{}) *PlatformCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PlatformCreate) SetStatus(v platform.Status) *PlatformCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PlatformCreate) SetNillableStatus(v *platform.Status) *PlatformCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPollInterval sets the "poll_interval" field.
func (_c *PlatformCreate) SetPollInterval(v int) *PlatformCreate {
	_c.mutation.SetPollInterval(v)
	return _c
}

// SetNillablePollInterval sets the "poll_interval" field if the given value is not nil.
func (_c *PlatformCreate) SetNillablePollInterval(v *int) *PlatformCreate {
	if v != nil {
		_c.SetPollInterval(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PlatformCreate) SetCreatedAt(v time.Time) *PlatformCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PlatformCreate) SetNillableCreatedAt(v *time.Time) *PlatformCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PlatformCreate) SetUpdatedAt(v time.Time) *PlatformCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PlatformCreate) SetNillableUpdatedAt(v *time.Time) *PlatformCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PlatformCreate) SetID(v int64) *PlatformCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddStreamerIDs adds the "streamers" edge to the Streamer entity by IDs.
func (_c *PlatformCreate) AddStreamerIDs(ids ...int64) *PlatformCreate {
	_c.mutation.AddStreamerIDs(ids...)
	return _c
}

// AddStreamers adds the "streamers" edges to the Streamer entity.
func (_c *PlatformCreate) AddStreamers(v ...*Streamer) *PlatformCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStreamerIDs(ids...)
}

// Mutation returns the PlatformMutation object of the builder.
func (_c *PlatformCreate) Mutation() *PlatformMutation {
	return _c.mutation
}

// Save creates the Platform in the database.
func (_c *PlatformCreate) Save(ctx context.Context) (*Platform, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlatformCreate) SaveX(ctx context.Context) *Platform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlatformCreate) defaults() error {
	if _, ok := _c.mutation.Status(); !ok {
		v := platform.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.PollInterval(); !ok {
		v := platform.DefaultPollInterval
		_c.mutation.SetPollInterval(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if platform.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized platform.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := platform.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if platform.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized platform.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := platform.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlatformCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Platform.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := platform.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Platform.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformType(); !ok {
		return &ValidationError{Name: "platform_type", err: errors.New(`ent: missing required field "Platform.platform_type"`)}
	}
	if v, ok := _c.mutation.PlatformType(); ok {
		if err := platform.PlatformTypeValidator(v); err != nil {
			return &ValidationError{Name: "platform_type", err: fmt.Errorf(`ent: validator failed for field "Platform.platform_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Platform.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := platform.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Platform.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PollInterval(); !ok {
		return &ValidationError{Name: "poll_interval", err: errors.New(`ent: missing required field "Platform.poll_interval"`)}
	}
	if v, ok := _c.mutation.PollInterval(); ok {
		if err := platform.PollIntervalValidator(v); err != nil {
			return &ValidationError{Name: "poll_interval", err: fmt.Errorf(`ent: validator failed for field "Platform.poll_interval": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Platform.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Platform.updated_at"`)}
	}
	return nil
}

func (_c *PlatformCreate) sqlSave(ctx context.Context) (*Platform, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlatformCreate) createSpec() (*Platform, *sqlgraph.CreateSpec) {
	var (
		_node = &Platform{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(platform.Table, sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeleteAt(); ok {
		_spec.SetField(platform.FieldDeleteAt, field.TypeTime, value)
		_node.DeleteAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(platform.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.PlatformType(); ok {
		_spec.SetField(platform.FieldPlatformType, field.TypeEnum, value)
		_node.PlatformType = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(platform.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(platform.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PollInterval(); ok {
		_spec.SetField(platform.FieldPollInterval, field.TypeInt, value)
		_node.PollInterval = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(platform.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(platform.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.StreamersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.StreamersTable,
			Columns: []string{platform.StreamersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PlatformCreateBulk is the builder for creating many Platform entities in bulk.
type PlatformCreateBulk struct {
	config
	err      error
	builders []*PlatformCreate
}

// Save creates the Platform entities in the database.
func (_c *PlatformCreateBulk) Save(ctx context.Context) ([]*Platform, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Platform, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlatformMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlatformCreateBulk) SaveX(ctx context.Context) []*Platform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlatformCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlatformCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
