// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/platform"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/predicate"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
)

// PlatformUpdate is the builder for updating Platform entities.
type PlatformUpdate struct {
	config
	hooks    []Hook
	mutation *PlatformMutation
}

// Where appends a list predicates to the PlatformUpdate builder.
func (_u *PlatformUpdate) Where(ps ...predicate.Platform) *PlatformUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeleteAt sets the "delete_at" field.
func (_u *PlatformUpdate) SetDeleteAt(v time.Time) *PlatformUpdate {
	_u.mutation.SetDeleteAt(v)
	return _u
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillableDeleteAt(v *time.Time) *PlatformUpdate {
	if v != nil {
		_u.SetDeleteAt(*v)
	}
	return _u
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (_u *PlatformUpdate) ClearDeleteAt() *PlatformUpdate {
	_u.mutation.ClearDeleteAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PlatformUpdate) SetName(v string) *PlatformUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillableName(v *string) *PlatformUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *PlatformUpdate) SetConfig(v map[string]interface{}) *PlatformUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *PlatformUpdate) ClearConfig() *PlatformUpdate {
	_u.mutation.ClearConfig()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PlatformUpdate) SetStatus(v platform.Status) *PlatformUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillableStatus(v *platform.Status) *PlatformUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPollInterval sets the "poll_interval" field.
func (_u *PlatformUpdate) SetPollInterval(v int) *PlatformUpdate {
	_u.mutation.ResetPollInterval()
	_u.mutation.SetPollInterval(v)
	return _u
}

// SetNillablePollInterval sets the "poll_interval" field if the given value is not nil.
func (_u *PlatformUpdate) SetNillablePollInterval(v *int) *PlatformUpdate {
	if v != nil {
		_u.SetPollInterval(*v)
	}
	return _u
}

// AddPollInterval adds value to the "poll_interval" field.
func (_u *PlatformUpdate) AddPollInterval(v int) *PlatformUpdate {
	_u.mutation.AddPollInterval(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformUpdate) SetUpdatedAt(v time.Time) *PlatformUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddStreamerIDs adds the "streamers" edge to the Streamer entity by IDs.
func (_u *PlatformUpdate) AddStreamerIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.AddStreamerIDs(ids...)
	return _u
}

// AddStreamers adds the "streamers" edges to the Streamer entity.
func (_u *PlatformUpdate) AddStreamers(v ...*Streamer) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStreamerIDs(ids...)
}

// Mutation returns the PlatformMutation object of the builder.
func (_u *PlatformUpdate) Mutation() *PlatformMutation {
	return _u.mutation
}

// ClearStreamers clears all "streamers" edges to the Streamer entity.
func (_u *PlatformUpdate) ClearStreamers() *PlatformUpdate {
	_u.mutation.ClearStreamers()
	return _u
}

// RemoveStreamerIDs removes the "streamers" edge to Streamer entities by IDs.
func (_u *PlatformUpdate) RemoveStreamerIDs(ids ...int64) *PlatformUpdate {
	_u.mutation.RemoveStreamerIDs(ids...)
	return _u
}

// RemoveStreamers removes "streamers" edges to Streamer entities.
func (_u *PlatformUpdate) RemoveStreamers(v ...*Streamer) *PlatformUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStreamerIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlatformUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlatformUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if platform.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized platform.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := platform.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := platform.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Platform.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := platform.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Platform.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PollInterval(); ok {
		if err := platform.PollIntervalValidator(v); err != nil {
			return &ValidationError{Name: "poll_interval", err: fmt.Errorf(`ent: validator failed for field "Platform.poll_interval": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platform.Table, platform.Columns, sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeleteAt(); ok {
		_spec.SetField(platform.FieldDeleteAt, field.TypeTime, value)
	}
	if _u.mutation.DeleteAtCleared() {
		_spec.ClearField(platform.FieldDeleteAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(platform.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(platform.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(platform.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(platform.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PollInterval(); ok {
		_spec.SetField(platform.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollInterval(); ok {
		_spec.AddField(platform.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platform.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StreamersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.StreamersTable,
			Columns: []string{platform.StreamersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStreamersIDs(); len(nodes) > 0 && !_u.mutation.StreamersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.StreamersTable,
			Columns: []string{platform.StreamersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StreamersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.StreamersTable,
			Columns: []string{platform.StreamersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlatformUpdateOne is the builder for updating a single Platform entity.
type PlatformUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlatformMutation
}

// SetDeleteAt sets the "delete_at" field.
func (_u *PlatformUpdateOne) SetDeleteAt(v time.Time) *PlatformUpdateOne {
	_u.mutation.SetDeleteAt(v)
	return _u
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillableDeleteAt(v *time.Time) *PlatformUpdateOne {
	if v != nil {
		_u.SetDeleteAt(*v)
	}
	return _u
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (_u *PlatformUpdateOne) ClearDeleteAt() *PlatformUpdateOne {
	_u.mutation.ClearDeleteAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PlatformUpdateOne) SetName(v string) *PlatformUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillableName(v *string) *PlatformUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetConfig sets the "config" field.
func (_u *PlatformUpdateOne) SetConfig(v map[string]interface{}) *PlatformUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// ClearConfig clears the value of the "config" field.
func (_u *PlatformUpdateOne) ClearConfig() *PlatformUpdateOne {
	_u.mutation.ClearConfig()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PlatformUpdateOne) SetStatus(v platform.Status) *PlatformUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillableStatus(v *platform.Status) *PlatformUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPollInterval sets the "poll_interval" field.
func (_u *PlatformUpdateOne) SetPollInterval(v int) *PlatformUpdateOne {
	_u.mutation.ResetPollInterval()
	_u.mutation.SetPollInterval(v)
	return _u
}

// SetNillablePollInterval sets the "poll_interval" field if the given value is not nil.
func (_u *PlatformUpdateOne) SetNillablePollInterval(v *int) *PlatformUpdateOne {
	if v != nil {
		_u.SetPollInterval(*v)
	}
	return _u
}

// AddPollInterval adds value to the "poll_interval" field.
func (_u *PlatformUpdateOne) AddPollInterval(v int) *PlatformUpdateOne {
	_u.mutation.AddPollInterval(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PlatformUpdateOne) SetUpdatedAt(v time.Time) *PlatformUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddStreamerIDs adds the "streamers" edge to the Streamer entity by IDs.
func (_u *PlatformUpdateOne) AddStreamerIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.AddStreamerIDs(ids...)
	return _u
}

// AddStreamers adds the "streamers" edges to the Streamer entity.
func (_u *PlatformUpdateOne) AddStreamers(v ...*Streamer) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddStreamerIDs(ids...)
}

// Mutation returns the PlatformMutation object of the builder.
func (_u *PlatformUpdateOne) Mutation() *PlatformMutation {
	return _u.mutation
}

// ClearStreamers clears all "streamers" edges to the Streamer entity.
func (_u *PlatformUpdateOne) ClearStreamers() *PlatformUpdateOne {
	_u.mutation.ClearStreamers()
	return _u
}

// RemoveStreamerIDs removes the "streamers" edge to Streamer entities by IDs.
func (_u *PlatformUpdateOne) RemoveStreamerIDs(ids ...int64) *PlatformUpdateOne {
	_u.mutation.RemoveStreamerIDs(ids...)
	return _u
}

// RemoveStreamers removes "streamers" edges to Streamer entities.
func (_u *PlatformUpdateOne) RemoveStreamers(v ...*Streamer) *PlatformUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveStreamerIDs(ids...)
}

// Where appends a list predicates to the PlatformUpdate builder.
func (_u *PlatformUpdateOne) Where(ps ...predicate.Platform) *PlatformUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlatformUpdateOne) Select(field string, fields ...string) *PlatformUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Platform entity.
func (_u *PlatformUpdateOne) Save(ctx context.Context) (*Platform, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlatformUpdateOne) SaveX(ctx context.Context) *Platform {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlatformUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlatformUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PlatformUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if platform.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized platform.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := platform.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlatformUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := platform.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Platform.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := platform.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Platform.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PollInterval(); ok {
		if err := platform.PollIntervalValidator(v); err != nil {
			return &ValidationError{Name: "poll_interval", err: fmt.Errorf(`ent: validator failed for field "Platform.poll_interval": %w`, err)}
		}
	}
	return nil
}

func (_u *PlatformUpdateOne) sqlSave(ctx context.Context) (_node *Platform, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(platform.Table, platform.Columns, sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Platform.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, platform.FieldID)
		for _, f := range fields {
			if !platform.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != platform.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeleteAt(); ok {
		_spec.SetField(platform.FieldDeleteAt, field.TypeTime, value)
	}
	if _u.mutation.DeleteAtCleared() {
		_spec.ClearField(platform.FieldDeleteAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(platform.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(platform.FieldConfig, field.TypeJSON, value)
	}
	if _u.mutation.ConfigCleared() {
		_spec.ClearField(platform.FieldConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(platform.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PollInterval(); ok {
		_spec.SetField(platform.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPollInterval(); ok {
		_spec.AddField(platform.FieldPollInterval, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(platform.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.StreamersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.StreamersTable,
			Columns: []string{platform.StreamersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedStreamersIDs(); len(nodes) > 0 && !_u.mutation.StreamersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.StreamersTable,
			Columns: []string{platform.StreamersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StreamersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   platform.StreamersTable,
			Columns: []string{platform.StreamersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Platform{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{platform.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
