// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/userfollowedstreamer"
)

// StreamerCreate is the builder for creating a Streamer entity.
type StreamerCreate struct {
	config
	mutation *StreamerMutation
	hooks    []Hook
}

// SetPlatformType sets the "platform_type" field.
func (_c *StreamerCreate) SetPlatformType(v string) *StreamerCreate {
	_c.mutation.SetPlatformType(v)
	return _c
}

// SetPlatformStreamerID sets the "platform_streamer_id" field.
func (_c *StreamerCreate) SetPlatformStreamerID(v string) *StreamerCreate {
	_c.mutation.SetPlatformStreamerID(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *StreamerCreate) SetDisplayName(v string) *StreamerCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *StreamerCreate) SetAvatarURL(v string) *StreamerCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableAvatarURL(v *string) *StreamerCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetRoomURL sets the "room_url" field.
func (_c *StreamerCreate) SetRoomURL(v string) *StreamerCreate {
	_c.mutation.SetRoomURL(v)
	return _c
}

// SetNillableRoomURL sets the "room_url" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableRoomURL(v *string) *StreamerCreate {
	if v != nil {
		_c.SetRoomURL(*v)
	}
	return _c
}

// SetBio sets the "bio" field.
func (_c *StreamerCreate) SetBio(v string) *StreamerCreate {
	_c.mutation.SetBio(v)
	return _c
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableBio(v *string) *StreamerCreate {
	if v != nil {
		_c.SetBio(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *StreamerCreate) SetTags(v []string) *StreamerCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetLastSyncedAt sets the "last_synced_at" field.
func (_c *StreamerCreate) SetLastSyncedAt(v time.Time) *StreamerCreate {
	_c.mutation.SetLastSyncedAt(v)
	return _c
}

// SetNillableLastSyncedAt sets the "last_synced_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableLastSyncedAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetLastSyncedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StreamerCreate) SetCreatedAt(v time.Time) *StreamerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableCreatedAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StreamerCreate) SetUpdatedAt(v time.Time) *StreamerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableUpdatedAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StreamerCreate) SetID(v int64) *StreamerCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddFollowerIDs adds the "followers" edge to the UserFollowedStreamer entity by IDs.
func (_c *StreamerCreate) AddFollowerIDs(ids ...int64) *StreamerCreate {
	_c.mutation.AddFollowerIDs(ids...)
	return _c
}

// AddFollowers adds the "followers" edges to the UserFollowedStreamer entity.
func (_c *StreamerCreate) AddFollowers(v ...*UserFollowedStreamer) *StreamerCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFollowerIDs(ids...)
}

// Mutation returns the StreamerMutation object of the builder.
func (_c *StreamerCreate) Mutation() *StreamerMutation {
	return _c.mutation
}

// Save creates the Streamer in the database.
func (_c *StreamerCreate) Save(ctx context.Context) (*Streamer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StreamerCreate) SaveX(ctx context.Context) *Streamer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StreamerCreate) defaults() {
	if _, ok := _c.mutation.Tags(); !ok {
		v := streamer.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := streamer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := streamer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StreamerCreate) check() error {
	if _, ok := _c.mutation.PlatformType(); !ok {
		return &ValidationError{Name: "platform_type", err: errors.New(`ent: missing required field "Streamer.platform_type"`)}
	}
	if v, ok := _c.mutation.PlatformType(); ok {
		if err := streamer.PlatformTypeValidator(v); err != nil {
			return &ValidationError{Name: "platform_type", err: fmt.Errorf(`ent: validator failed for field "Streamer.platform_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformStreamerID(); !ok {
		return &ValidationError{Name: "platform_streamer_id", err: errors.New(`ent: missing required field "Streamer.platform_streamer_id"`)}
	}
	if v, ok := _c.mutation.PlatformStreamerID(); ok {
		if err := streamer.PlatformStreamerIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_streamer_id", err: fmt.Errorf(`ent: validator failed for field "Streamer.platform_streamer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "Streamer.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := streamer.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "Streamer.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Streamer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Streamer.updated_at"`)}
	}
	return nil
}

func (_c *StreamerCreate) sqlSave(ctx context.Context) (*Streamer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StreamerCreate) createSpec() (*Streamer, *sqlgraph.CreateSpec) {
	var (
		_node = &Streamer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(streamer.Table, sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PlatformType(); ok {
		_spec.SetField(streamer.FieldPlatformType, field.TypeString, value)
		_node.PlatformType = value
	}
	if value, ok := _c.mutation.PlatformStreamerID(); ok {
		_spec.SetField(streamer.FieldPlatformStreamerID, field.TypeString, value)
		_node.PlatformStreamerID = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(streamer.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(streamer.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = &value
	}
	if value, ok := _c.mutation.RoomURL(); ok {
		_spec.SetField(streamer.FieldRoomURL, field.TypeString, value)
		_node.RoomURL = &value
	}
	if value, ok := _c.mutation.Bio(); ok {
		_spec.SetField(streamer.FieldBio, field.TypeString, value)
		_node.Bio = &value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(streamer.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.LastSyncedAt(); ok {
		_spec.SetField(streamer.FieldLastSyncedAt, field.TypeTime, value)
		_node.LastSyncedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(streamer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(streamer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.FollowersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   streamer.FollowersTable,
			Columns: []string{streamer.FollowersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfollowedstreamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StreamerCreateBulk is the builder for creating many Streamer entities in bulk.
type StreamerCreateBulk struct {
	config
	err      error
	builders []*StreamerCreate
}

// Save creates the Streamer entities in the database.
func (_c *StreamerCreateBulk) Save(ctx context.Context) ([]*Streamer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Streamer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StreamerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StreamerCreateBulk) SaveX(ctx context.Context) []*Streamer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
