// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/platform"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/userfollowing"
)

// StreamerCreate is the builder for creating a Streamer entity.
type StreamerCreate struct {
	config
	mutation *StreamerMutation
	hooks    []Hook
}

// SetDeleteAt sets the "delete_at" field.
func (_c *StreamerCreate) SetDeleteAt(v time.Time) *StreamerCreate {
	_c.mutation.SetDeleteAt(v)
	return _c
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableDeleteAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetDeleteAt(*v)
	}
	return _c
}

// SetPlatformID sets the "platform_id" field.
func (_c *StreamerCreate) SetPlatformID(v int64) *StreamerCreate {
	_c.mutation.SetPlatformID(v)
	return _c
}

// SetPlatformStreamerID sets the "platform_streamer_id" field.
func (_c *StreamerCreate) SetPlatformStreamerID(v string) *StreamerCreate {
	_c.mutation.SetPlatformStreamerID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *StreamerCreate) SetName(v string) *StreamerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAvatar sets the "avatar" field.
func (_c *StreamerCreate) SetAvatar(v string) *StreamerCreate {
	_c.mutation.SetAvatar(v)
	return _c
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableAvatar(v *string) *StreamerCreate {
	if v != nil {
		_c.SetAvatar(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *StreamerCreate) SetDescription(v string) *StreamerCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableDescription(v *string) *StreamerCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRoomURL sets the "room_url" field.
func (_c *StreamerCreate) SetRoomURL(v string) *StreamerCreate {
	_c.mutation.SetRoomURL(v)
	return _c
}

// SetNillableRoomURL sets the "room_url" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableRoomURL(v *string) *StreamerCreate {
	if v != nil {
		_c.SetRoomURL(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *StreamerCreate) SetLastCheckedAt(v time.Time) *StreamerCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableLastCheckedAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetIsLive sets the "is_live" field.
func (_c *StreamerCreate) SetIsLive(v bool) *StreamerCreate {
	_c.mutation.SetIsLive(v)
	return _c
}

// SetNillableIsLive sets the "is_live" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableIsLive(v *bool) *StreamerCreate {
	if v != nil {
		_c.SetIsLive(*v)
	}
	return _c
}

// SetLastLiveAt sets the "last_live_at" field.
func (_c *StreamerCreate) SetLastLiveAt(v time.Time) *StreamerCreate {
	_c.mutation.SetLastLiveAt(v)
	return _c
}

// SetNillableLastLiveAt sets the "last_live_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableLastLiveAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetLastLiveAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StreamerCreate) SetCreatedAt(v time.Time) *StreamerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableCreatedAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StreamerCreate) SetUpdatedAt(v time.Time) *StreamerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StreamerCreate) SetNillableUpdatedAt(v *time.Time) *StreamerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StreamerCreate) SetID(v int64) *StreamerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetPlatform sets the "platform" edge to the Platform entity.
func (_c *StreamerCreate) SetPlatform(v *Platform) *StreamerCreate {
	return _c.SetPlatformID(v.ID)
}

// AddFollowingIDs adds the "followings" edge to the UserFollowing entity by IDs.
func (_c *StreamerCreate) AddFollowingIDs(ids ...int64) *StreamerCreate {
	_c.mutation.AddFollowingIDs(ids...)
	return _c
}

// AddFollowings adds the "followings" edges to the UserFollowing entity.
func (_c *StreamerCreate) AddFollowings(v ...*UserFollowing) *StreamerCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFollowingIDs(ids...)
}

// Mutation returns the StreamerMutation object of the builder.
func (_c *StreamerCreate) Mutation() *StreamerMutation {
	return _c.mutation
}

// Save creates the Streamer in the database.
func (_c *StreamerCreate) Save(ctx context.Context) (*Streamer, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StreamerCreate) SaveX(ctx context.Context) *Streamer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StreamerCreate) defaults() error {
	if _, ok := _c.mutation.IsLive(); !ok {
		v := streamer.DefaultIsLive
		_c.mutation.SetIsLive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if streamer.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized streamer.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := streamer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if streamer.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized streamer.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := streamer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *StreamerCreate) check() error {
	if _, ok := _c.mutation.PlatformID(); !ok {
		return &ValidationError{Name: "platform_id", err: errors.New(`ent: missing required field "Streamer.platform_id"`)}
	}
	if v, ok := _c.mutation.PlatformID(); ok {
		if err := streamer.PlatformIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_id", err: fmt.Errorf(`ent: validator failed for field "Streamer.platform_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlatformStreamerID(); !ok {
		return &ValidationError{Name: "platform_streamer_id", err: errors.New(`ent: missing required field "Streamer.platform_streamer_id"`)}
	}
	if v, ok := _c.mutation.PlatformStreamerID(); ok {
		if err := streamer.PlatformStreamerIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_streamer_id", err: fmt.Errorf(`ent: validator failed for field "Streamer.platform_streamer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Streamer.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := streamer.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Streamer.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsLive(); !ok {
		return &ValidationError{Name: "is_live", err: errors.New(`ent: missing required field "Streamer.is_live"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Streamer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Streamer.updated_at"`)}
	}
	if len(_c.mutation.PlatformIDs()) == 0 {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required edge "Streamer.platform"`)}
	}
	return nil
}

func (_c *StreamerCreate) sqlSave(ctx context.Context) (*Streamer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StreamerCreate) createSpec() (*Streamer, *sqlgraph.CreateSpec) {
	var (
		_node = &Streamer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(streamer.Table, sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeleteAt(); ok {
		_spec.SetField(streamer.FieldDeleteAt, field.TypeTime, value)
		_node.DeleteAt = value
	}
	if value, ok := _c.mutation.PlatformStreamerID(); ok {
		_spec.SetField(streamer.FieldPlatformStreamerID, field.TypeString, value)
		_node.PlatformStreamerID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(streamer.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Avatar(); ok {
		_spec.SetField(streamer.FieldAvatar, field.TypeString, value)
		_node.Avatar = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(streamer.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.RoomURL(); ok {
		_spec.SetField(streamer.FieldRoomURL, field.TypeString, value)
		_node.RoomURL = value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(streamer.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.IsLive(); ok {
		_spec.SetField(streamer.FieldIsLive, field.TypeBool, value)
		_node.IsLive = value
	}
	if value, ok := _c.mutation.LastLiveAt(); ok {
		_spec.SetField(streamer.FieldLastLiveAt, field.TypeTime, value)
		_node.LastLiveAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(streamer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(streamer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PlatformIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   streamer.PlatformTable,
			Columns: []string{streamer.PlatformColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(platform.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlatformID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FollowingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   streamer.FollowingsTable,
			Columns: []string{streamer.FollowingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userfollowing.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StreamerCreateBulk is the builder for creating many Streamer entities in bulk.
type StreamerCreateBulk struct {
	config
	err      error
	builders []*StreamerCreate
}

// Save creates the Streamer entities in the database.
func (_c *StreamerCreateBulk) Save(ctx context.Context) ([]*Streamer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Streamer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StreamerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StreamerCreateBulk) SaveX(ctx context.Context) []*Streamer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
