// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/platform"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
)

// Streamer is the model entity for the Streamer schema.
type Streamer struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// DeleteAt holds the value of the "delete_at" field.
	DeleteAt time.Time `json:"delete_at,omitempty"`
	// PlatformID holds the value of the "platform_id" field.
	PlatformID int64 `json:"platform_id,omitempty"`
	// PlatformStreamerID holds the value of the "platform_streamer_id" field.
	PlatformStreamerID string `json:"platform_streamer_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Avatar holds the value of the "avatar" field.
	Avatar string `json:"avatar,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// RoomURL holds the value of the "room_url" field.
	RoomURL string `json:"room_url,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// IsLive holds the value of the "is_live" field.
	IsLive bool `json:"is_live,omitempty"`
	// LastLiveAt holds the value of the "last_live_at" field.
	LastLiveAt *time.Time `json:"last_live_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StreamerQuery when eager-loading is set.
	Edges        StreamerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StreamerEdges holds the relations/edges for other nodes in the graph.
type StreamerEdges struct {
	// Platform holds the value of the platform edge.
	Platform *Platform `json:"platform,omitempty"`
	// Followings holds the value of the followings edge.
	Followings []*UserFollowing `json:"followings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlatformOrErr returns the Platform value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StreamerEdges) PlatformOrErr() (*Platform, error) {
	if e.Platform != nil {
		return e.Platform, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: platform.Label}
	}
	return nil, &NotLoadedError{edge: "platform"}
}

// FollowingsOrErr returns the Followings value or an error if the edge
// was not loaded in eager-loading.
func (e StreamerEdges) FollowingsOrErr() ([]*UserFollowing, error) {
	if e.loadedTypes[1] {
		return e.Followings, nil
	}
	return nil, &NotLoadedError{edge: "followings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Streamer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case streamer.FieldIsLive:
			values[i] = new(sql.NullBool)
		case streamer.FieldID, streamer.FieldPlatformID:
			values[i] = new(sql.NullInt64)
		case streamer.FieldPlatformStreamerID, streamer.FieldName, streamer.FieldAvatar, streamer.FieldDescription, streamer.FieldRoomURL:
			values[i] = new(sql.NullString)
		case streamer.FieldDeleteAt, streamer.FieldLastCheckedAt, streamer.FieldLastLiveAt, streamer.FieldCreatedAt, streamer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Streamer fields.
func (_m *Streamer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case streamer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case streamer.FieldDeleteAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_at", values[i])
			} else if value.Valid {
				_m.DeleteAt = value.Time
			}
		case streamer.FieldPlatformID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_id", values[i])
			} else if value.Valid {
				_m.PlatformID = value.Int64
			}
		case streamer.FieldPlatformStreamerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_streamer_id", values[i])
			} else if value.Valid {
				_m.PlatformStreamerID = value.String
			}
		case streamer.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case streamer.FieldAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar", values[i])
			} else if value.Valid {
				_m.Avatar = value.String
			}
		case streamer.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case streamer.FieldRoomURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field room_url", values[i])
			} else if value.Valid {
				_m.RoomURL = value.String
			}
		case streamer.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case streamer.FieldIsLive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_live", values[i])
			} else if value.Valid {
				_m.IsLive = value.Bool
			}
		case streamer.FieldLastLiveAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_live_at", values[i])
			} else if value.Valid {
				_m.LastLiveAt = new(time.Time)
				*_m.LastLiveAt = value.Time
			}
		case streamer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case streamer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Streamer.
// This includes values selected through modifiers, order, etc.
func (_m *Streamer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlatform queries the "platform" edge of the Streamer entity.
func (_m *Streamer) QueryPlatform() *PlatformQuery {
	return NewStreamerClient(_m.config).QueryPlatform(_m)
}

// QueryFollowings queries the "followings" edge of the Streamer entity.
func (_m *Streamer) QueryFollowings() *UserFollowingQuery {
	return NewStreamerClient(_m.config).QueryFollowings(_m)
}

// Update returns a builder for updating this Streamer.
// Note that you need to call Streamer.Unwrap() before calling this method if this Streamer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Streamer) Update() *StreamerUpdateOne {
	return NewStreamerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Streamer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Streamer) Unwrap() *Streamer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Streamer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Streamer) String() string {
	var builder strings.Builder
	builder.WriteString("Streamer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("delete_at=")
	builder.WriteString(_m.DeleteAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("platform_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlatformID))
	builder.WriteString(", ")
	builder.WriteString("platform_streamer_id=")
	builder.WriteString(_m.PlatformStreamerID)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("avatar=")
	builder.WriteString(_m.Avatar)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("room_url=")
	builder.WriteString(_m.RoomURL)
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_live=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsLive))
	builder.WriteString(", ")
	if v := _m.LastLiveAt; v != nil {
		builder.WriteString("last_live_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Streamers is a parsable slice of Streamer.
type Streamers []*Streamer
