// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/predicate"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamingplatform"
)

// StreamingPlatformDelete is the builder for deleting a StreamingPlatform entity.
type StreamingPlatformDelete struct {
	config
	hooks    []Hook
	mutation *StreamingPlatformMutation
}

// Where appends a list predicates to the StreamingPlatformDelete builder.
func (_d *StreamingPlatformDelete) Where(ps ...predicate.StreamingPlatform) *StreamingPlatformDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StreamingPlatformDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StreamingPlatformDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StreamingPlatformDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(streamingplatform.Table, sqlgraph.NewFieldSpec(streamingplatform.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StreamingPlatformDeleteOne is the builder for deleting a single StreamingPlatform entity.
type StreamingPlatformDeleteOne struct {
	_d *StreamingPlatformDelete
}

// Where appends a list predicates to the StreamingPlatformDelete builder.
func (_d *StreamingPlatformDeleteOne) Where(ps ...predicate.StreamingPlatform) *StreamingPlatformDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StreamingPlatformDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{streamingplatform.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StreamingPlatformDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
