// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
)

// Streamer is the model entity for the Streamer schema.
type Streamer struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// PlatformType holds the value of the "platform_type" field.
	PlatformType string `json:"platform_type,omitempty"`
	// PlatformStreamerID holds the value of the "platform_streamer_id" field.
	PlatformStreamerID string `json:"platform_streamer_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL *string `json:"avatar_url,omitempty"`
	// RoomURL holds the value of the "room_url" field.
	RoomURL *string `json:"room_url,omitempty"`
	// Bio holds the value of the "bio" field.
	Bio *string `json:"bio,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// LastSyncedAt holds the value of the "last_synced_at" field.
	LastSyncedAt *time.Time `json:"last_synced_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StreamerQuery when eager-loading is set.
	Edges        StreamerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StreamerEdges holds the relations/edges for other nodes in the graph.
type StreamerEdges struct {
	// Followers holds the value of the followers edge.
	Followers []*UserFollowedStreamer `json:"followers,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FollowersOrErr returns the Followers value or an error if the edge
// was not loaded in eager-loading.
func (e StreamerEdges) FollowersOrErr() ([]*UserFollowedStreamer, error) {
	if e.loadedTypes[0] {
		return e.Followers, nil
	}
	return nil, &NotLoadedError{edge: "followers"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Streamer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case streamer.FieldTags:
			values[i] = new([]byte)
		case streamer.FieldID:
			values[i] = new(sql.NullInt64)
		case streamer.FieldPlatformType, streamer.FieldPlatformStreamerID, streamer.FieldDisplayName, streamer.FieldAvatarURL, streamer.FieldRoomURL, streamer.FieldBio:
			values[i] = new(sql.NullString)
		case streamer.FieldLastSyncedAt, streamer.FieldCreatedAt, streamer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Streamer fields.
func (_m *Streamer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case streamer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case streamer.FieldPlatformType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_type", values[i])
			} else if value.Valid {
				_m.PlatformType = value.String
			}
		case streamer.FieldPlatformStreamerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_streamer_id", values[i])
			} else if value.Valid {
				_m.PlatformStreamerID = value.String
			}
		case streamer.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case streamer.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = new(string)
				*_m.AvatarURL = value.String
			}
		case streamer.FieldRoomURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field room_url", values[i])
			} else if value.Valid {
				_m.RoomURL = new(string)
				*_m.RoomURL = value.String
			}
		case streamer.FieldBio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bio", values[i])
			} else if value.Valid {
				_m.Bio = new(string)
				*_m.Bio = value.String
			}
		case streamer.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case streamer.FieldLastSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_synced_at", values[i])
			} else if value.Valid {
				_m.LastSyncedAt = new(time.Time)
				*_m.LastSyncedAt = value.Time
			}
		case streamer.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case streamer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Streamer.
// This includes values selected through modifiers, order, etc.
func (_m *Streamer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFollowers queries the "followers" edge of the Streamer entity.
func (_m *Streamer) QueryFollowers() *UserFollowedStreamerQuery {
	return NewStreamerClient(_m.config).QueryFollowers(_m)
}

// Update returns a builder for updating this Streamer.
// Note that you need to call Streamer.Unwrap() before calling this method if this Streamer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Streamer) Update() *StreamerUpdateOne {
	return NewStreamerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Streamer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Streamer) Unwrap() *Streamer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Streamer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Streamer) String() string {
	var builder strings.Builder
	builder.WriteString("Streamer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("platform_type=")
	builder.WriteString(_m.PlatformType)
	builder.WriteString(", ")
	builder.WriteString("platform_streamer_id=")
	builder.WriteString(_m.PlatformStreamerID)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	if v := _m.AvatarURL; v != nil {
		builder.WriteString("avatar_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RoomURL; v != nil {
		builder.WriteString("room_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Bio; v != nil {
		builder.WriteString("bio=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tags))
	builder.WriteString(", ")
	if v := _m.LastSyncedAt; v != nil {
		builder.WriteString("last_synced_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Streamers is a parsable slice of Streamer.
type Streamers []*Streamer
