// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamingplatform"
)

// StreamingPlatformCreate is the builder for creating a StreamingPlatform entity.
type StreamingPlatformCreate struct {
	config
	mutation *StreamingPlatformMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (_c *StreamingPlatformCreate) SetType(v string) *StreamingPlatformCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetName sets the "name" field.
func (_c *StreamingPlatformCreate) SetName(v string) *StreamingPlatformCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *StreamingPlatformCreate) SetDescription(v string) *StreamingPlatformCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *StreamingPlatformCreate) SetNillableDescription(v *string) *StreamingPlatformCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *StreamingPlatformCreate) SetBaseURL(v string) *StreamingPlatformCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *StreamingPlatformCreate) SetLogoURL(v string) *StreamingPlatformCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_c *StreamingPlatformCreate) SetNillableLogoURL(v *string) *StreamingPlatformCreate {
	if v != nil {
		_c.SetLogoURL(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *StreamingPlatformCreate) SetEnabled(v bool) *StreamingPlatformCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *StreamingPlatformCreate) SetNillableEnabled(v *bool) *StreamingPlatformCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *StreamingPlatformCreate) SetPriority(v int) *StreamingPlatformCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *StreamingPlatformCreate) SetNillablePriority(v *int) *StreamingPlatformCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *StreamingPlatformCreate) SetMetadata(v map[string]string) *StreamingPlatformCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StreamingPlatformCreate) SetCreatedAt(v time.Time) *StreamingPlatformCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StreamingPlatformCreate) SetNillableCreatedAt(v *time.Time) *StreamingPlatformCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StreamingPlatformCreate) SetUpdatedAt(v time.Time) *StreamingPlatformCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StreamingPlatformCreate) SetNillableUpdatedAt(v *time.Time) *StreamingPlatformCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StreamingPlatformCreate) SetID(v int64) *StreamingPlatformCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the StreamingPlatformMutation object of the builder.
func (_c *StreamingPlatformCreate) Mutation() *StreamingPlatformMutation {
	return _c.mutation
}

// Save creates the StreamingPlatform in the database.
func (_c *StreamingPlatformCreate) Save(ctx context.Context) (*StreamingPlatform, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StreamingPlatformCreate) SaveX(ctx context.Context) *StreamingPlatform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamingPlatformCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamingPlatformCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StreamingPlatformCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := streamingplatform.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := streamingplatform.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := streamingplatform.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := streamingplatform.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := streamingplatform.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StreamingPlatformCreate) check() error {
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "StreamingPlatform.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := streamingplatform.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "StreamingPlatform.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StreamingPlatform.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := streamingplatform.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StreamingPlatform.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "StreamingPlatform.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := streamingplatform.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "StreamingPlatform.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "StreamingPlatform.enabled"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "StreamingPlatform.priority"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StreamingPlatform.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StreamingPlatform.updated_at"`)}
	}
	return nil
}

func (_c *StreamingPlatformCreate) sqlSave(ctx context.Context) (*StreamingPlatform, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StreamingPlatformCreate) createSpec() (*StreamingPlatform, *sqlgraph.CreateSpec) {
	var (
		_node = &StreamingPlatform{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(streamingplatform.Table, sqlgraph.NewFieldSpec(streamingplatform.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(streamingplatform.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(streamingplatform.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(streamingplatform.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(streamingplatform.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(streamingplatform.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(streamingplatform.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(streamingplatform.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(streamingplatform.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(streamingplatform.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(streamingplatform.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// StreamingPlatformCreateBulk is the builder for creating many StreamingPlatform entities in bulk.
type StreamingPlatformCreateBulk struct {
	config
	err      error
	builders []*StreamingPlatformCreate
}

// Save creates the StreamingPlatform entities in the database.
func (_c *StreamingPlatformCreateBulk) Save(ctx context.Context) ([]*StreamingPlatform, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StreamingPlatform, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StreamingPlatformMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StreamingPlatformCreateBulk) SaveX(ctx context.Context) []*StreamingPlatform {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StreamingPlatformCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StreamingPlatformCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
