// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/user"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/userfollowedstreamer"
)

// UserFollowedStreamerCreate is the builder for creating a UserFollowedStreamer entity.
type UserFollowedStreamerCreate struct {
	config
	mutation *UserFollowedStreamerMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserFollowedStreamerCreate) SetUserID(v int64) *UserFollowedStreamerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStreamerID sets the "streamer_id" field.
func (_c *UserFollowedStreamerCreate) SetStreamerID(v int64) *UserFollowedStreamerCreate {
	_c.mutation.SetStreamerID(v)
	return _c
}

// SetAlias sets the "alias" field.
func (_c *UserFollowedStreamerCreate) SetAlias(v string) *UserFollowedStreamerCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_c *UserFollowedStreamerCreate) SetNillableAlias(v *string) *UserFollowedStreamerCreate {
	if v != nil {
		_c.SetAlias(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *UserFollowedStreamerCreate) SetNotes(v string) *UserFollowedStreamerCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *UserFollowedStreamerCreate) SetNillableNotes(v *string) *UserFollowedStreamerCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetNotificationsEnabled sets the "notifications_enabled" field.
func (_c *UserFollowedStreamerCreate) SetNotificationsEnabled(v bool) *UserFollowedStreamerCreate {
	_c.mutation.SetNotificationsEnabled(v)
	return _c
}

// SetNillableNotificationsEnabled sets the "notifications_enabled" field if the given value is not nil.
func (_c *UserFollowedStreamerCreate) SetNillableNotificationsEnabled(v *bool) *UserFollowedStreamerCreate {
	if v != nil {
		_c.SetNotificationsEnabled(*v)
	}
	return _c
}

// SetNotificationChannelIds sets the "notification_channel_ids" field.
func (_c *UserFollowedStreamerCreate) SetNotificationChannelIds(v []int64) *UserFollowedStreamerCreate {
	_c.mutation.SetNotificationChannelIds(v)
	return _c
}

// SetLastNotificationSentAt sets the "last_notification_sent_at" field.
func (_c *UserFollowedStreamerCreate) SetLastNotificationSentAt(v time.Time) *UserFollowedStreamerCreate {
	_c.mutation.SetLastNotificationSentAt(v)
	return _c
}

// SetNillableLastNotificationSentAt sets the "last_notification_sent_at" field if the given value is not nil.
func (_c *UserFollowedStreamerCreate) SetNillableLastNotificationSentAt(v *time.Time) *UserFollowedStreamerCreate {
	if v != nil {
		_c.SetLastNotificationSentAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserFollowedStreamerCreate) SetCreatedAt(v time.Time) *UserFollowedStreamerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserFollowedStreamerCreate) SetNillableCreatedAt(v *time.Time) *UserFollowedStreamerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserFollowedStreamerCreate) SetUpdatedAt(v time.Time) *UserFollowedStreamerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserFollowedStreamerCreate) SetNillableUpdatedAt(v *time.Time) *UserFollowedStreamerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserFollowedStreamerCreate) SetID(v int64) *UserFollowedStreamerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserFollowedStreamerCreate) SetUser(v *User) *UserFollowedStreamerCreate {
	return _c.SetUserID(v.ID)
}

// SetStreamer sets the "streamer" edge to the Streamer entity.
func (_c *UserFollowedStreamerCreate) SetStreamer(v *Streamer) *UserFollowedStreamerCreate {
	return _c.SetStreamerID(v.ID)
}

// Mutation returns the UserFollowedStreamerMutation object of the builder.
func (_c *UserFollowedStreamerCreate) Mutation() *UserFollowedStreamerMutation {
	return _c.mutation
}

// Save creates the UserFollowedStreamer in the database.
func (_c *UserFollowedStreamerCreate) Save(ctx context.Context) (*UserFollowedStreamer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserFollowedStreamerCreate) SaveX(ctx context.Context) *UserFollowedStreamer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFollowedStreamerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFollowedStreamerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserFollowedStreamerCreate) defaults() {
	if _, ok := _c.mutation.NotificationsEnabled(); !ok {
		v := userfollowedstreamer.DefaultNotificationsEnabled
		_c.mutation.SetNotificationsEnabled(v)
	}
	if _, ok := _c.mutation.NotificationChannelIds(); !ok {
		v := userfollowedstreamer.DefaultNotificationChannelIds
		_c.mutation.SetNotificationChannelIds(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userfollowedstreamer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userfollowedstreamer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserFollowedStreamerCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserFollowedStreamer.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := userfollowedstreamer.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowedStreamer.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StreamerID(); !ok {
		return &ValidationError{Name: "streamer_id", err: errors.New(`ent: missing required field "UserFollowedStreamer.streamer_id"`)}
	}
	if v, ok := _c.mutation.StreamerID(); ok {
		if err := userfollowedstreamer.StreamerIDValidator(v); err != nil {
			return &ValidationError{Name: "streamer_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowedStreamer.streamer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotificationsEnabled(); !ok {
		return &ValidationError{Name: "notifications_enabled", err: errors.New(`ent: missing required field "UserFollowedStreamer.notifications_enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserFollowedStreamer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserFollowedStreamer.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserFollowedStreamer.user"`)}
	}
	if len(_c.mutation.StreamerIDs()) == 0 {
		return &ValidationError{Name: "streamer", err: errors.New(`ent: missing required edge "UserFollowedStreamer.streamer"`)}
	}
	return nil
}

func (_c *UserFollowedStreamerCreate) sqlSave(ctx context.Context) (*UserFollowedStreamer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserFollowedStreamerCreate) createSpec() (*UserFollowedStreamer, *sqlgraph.CreateSpec) {
	var (
		_node = &UserFollowedStreamer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userfollowedstreamer.Table, sqlgraph.NewFieldSpec(userfollowedstreamer.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(userfollowedstreamer.FieldAlias, field.TypeString, value)
		_node.Alias = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(userfollowedstreamer.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.NotificationsEnabled(); ok {
		_spec.SetField(userfollowedstreamer.FieldNotificationsEnabled, field.TypeBool, value)
		_node.NotificationsEnabled = value
	}
	if value, ok := _c.mutation.NotificationChannelIds(); ok {
		_spec.SetField(userfollowedstreamer.FieldNotificationChannelIds, field.TypeJSON, value)
		_node.NotificationChannelIds = value
	}
	if value, ok := _c.mutation.LastNotificationSentAt(); ok {
		_spec.SetField(userfollowedstreamer.FieldLastNotificationSentAt, field.TypeTime, value)
		_node.LastNotificationSentAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userfollowedstreamer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userfollowedstreamer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowedstreamer.UserTable,
			Columns: []string{userfollowedstreamer.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StreamerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowedstreamer.StreamerTable,
			Columns: []string{userfollowedstreamer.StreamerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StreamerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserFollowedStreamerCreateBulk is the builder for creating many UserFollowedStreamer entities in bulk.
type UserFollowedStreamerCreateBulk struct {
	config
	err      error
	builders []*UserFollowedStreamerCreate
}

// Save creates the UserFollowedStreamer entities in the database.
func (_c *UserFollowedStreamerCreateBulk) Save(ctx context.Context) ([]*UserFollowedStreamer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserFollowedStreamer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserFollowedStreamerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserFollowedStreamerCreateBulk) SaveX(ctx context.Context) []*UserFollowedStreamer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFollowedStreamerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFollowedStreamerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
