// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/user"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/userfollowing"
)

// UserFollowingCreate is the builder for creating a UserFollowing entity.
type UserFollowingCreate struct {
	config
	mutation *UserFollowingMutation
	hooks    []Hook
}

// SetDeleteAt sets the "delete_at" field.
func (_c *UserFollowingCreate) SetDeleteAt(v time.Time) *UserFollowingCreate {
	_c.mutation.SetDeleteAt(v)
	return _c
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (_c *UserFollowingCreate) SetNillableDeleteAt(v *time.Time) *UserFollowingCreate {
	if v != nil {
		_c.SetDeleteAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserFollowingCreate) SetUserID(v int64) *UserFollowingCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStreamerID sets the "streamer_id" field.
func (_c *UserFollowingCreate) SetStreamerID(v int64) *UserFollowingCreate {
	_c.mutation.SetStreamerID(v)
	return _c
}

// SetNotificationEnabled sets the "notification_enabled" field.
func (_c *UserFollowingCreate) SetNotificationEnabled(v bool) *UserFollowingCreate {
	_c.mutation.SetNotificationEnabled(v)
	return _c
}

// SetNillableNotificationEnabled sets the "notification_enabled" field if the given value is not nil.
func (_c *UserFollowingCreate) SetNillableNotificationEnabled(v *bool) *UserFollowingCreate {
	if v != nil {
		_c.SetNotificationEnabled(*v)
	}
	return _c
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_c *UserFollowingCreate) SetLastNotifiedAt(v time.Time) *UserFollowingCreate {
	_c.mutation.SetLastNotifiedAt(v)
	return _c
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_c *UserFollowingCreate) SetNillableLastNotifiedAt(v *time.Time) *UserFollowingCreate {
	if v != nil {
		_c.SetLastNotifiedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserFollowingCreate) SetCreatedAt(v time.Time) *UserFollowingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserFollowingCreate) SetNillableCreatedAt(v *time.Time) *UserFollowingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserFollowingCreate) SetUpdatedAt(v time.Time) *UserFollowingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserFollowingCreate) SetNillableUpdatedAt(v *time.Time) *UserFollowingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserFollowingCreate) SetID(v int64) *UserFollowingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserFollowingCreate) SetUser(v *User) *UserFollowingCreate {
	return _c.SetUserID(v.ID)
}

// SetStreamer sets the "streamer" edge to the Streamer entity.
func (_c *UserFollowingCreate) SetStreamer(v *Streamer) *UserFollowingCreate {
	return _c.SetStreamerID(v.ID)
}

// Mutation returns the UserFollowingMutation object of the builder.
func (_c *UserFollowingCreate) Mutation() *UserFollowingMutation {
	return _c.mutation
}

// Save creates the UserFollowing in the database.
func (_c *UserFollowingCreate) Save(ctx context.Context) (*UserFollowing, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserFollowingCreate) SaveX(ctx context.Context) *UserFollowing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFollowingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFollowingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserFollowingCreate) defaults() error {
	if _, ok := _c.mutation.NotificationEnabled(); !ok {
		v := userfollowing.DefaultNotificationEnabled
		_c.mutation.SetNotificationEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if userfollowing.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized userfollowing.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := userfollowing.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if userfollowing.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userfollowing.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userfollowing.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserFollowingCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserFollowing.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := userfollowing.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowing.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StreamerID(); !ok {
		return &ValidationError{Name: "streamer_id", err: errors.New(`ent: missing required field "UserFollowing.streamer_id"`)}
	}
	if v, ok := _c.mutation.StreamerID(); ok {
		if err := userfollowing.StreamerIDValidator(v); err != nil {
			return &ValidationError{Name: "streamer_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowing.streamer_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NotificationEnabled(); !ok {
		return &ValidationError{Name: "notification_enabled", err: errors.New(`ent: missing required field "UserFollowing.notification_enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserFollowing.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserFollowing.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserFollowing.user"`)}
	}
	if len(_c.mutation.StreamerIDs()) == 0 {
		return &ValidationError{Name: "streamer", err: errors.New(`ent: missing required edge "UserFollowing.streamer"`)}
	}
	return nil
}

func (_c *UserFollowingCreate) sqlSave(ctx context.Context) (*UserFollowing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserFollowingCreate) createSpec() (*UserFollowing, *sqlgraph.CreateSpec) {
	var (
		_node = &UserFollowing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userfollowing.Table, sqlgraph.NewFieldSpec(userfollowing.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.DeleteAt(); ok {
		_spec.SetField(userfollowing.FieldDeleteAt, field.TypeTime, value)
		_node.DeleteAt = value
	}
	if value, ok := _c.mutation.NotificationEnabled(); ok {
		_spec.SetField(userfollowing.FieldNotificationEnabled, field.TypeBool, value)
		_node.NotificationEnabled = value
	}
	if value, ok := _c.mutation.LastNotifiedAt(); ok {
		_spec.SetField(userfollowing.FieldLastNotifiedAt, field.TypeTime, value)
		_node.LastNotifiedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userfollowing.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userfollowing.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.UserTable,
			Columns: []string{userfollowing.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StreamerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.StreamerTable,
			Columns: []string{userfollowing.StreamerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StreamerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserFollowingCreateBulk is the builder for creating many UserFollowing entities in bulk.
type UserFollowingCreateBulk struct {
	config
	err      error
	builders []*UserFollowingCreate
}

// Save creates the UserFollowing entities in the database.
func (_c *UserFollowingCreateBulk) Save(ctx context.Context) ([]*UserFollowing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserFollowing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserFollowingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserFollowingCreateBulk) SaveX(ctx context.Context) []*UserFollowing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserFollowingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserFollowingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
