// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/predicate"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/streamer"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/user"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/userfollowing"
)

// UserFollowingUpdate is the builder for updating UserFollowing entities.
type UserFollowingUpdate struct {
	config
	hooks    []Hook
	mutation *UserFollowingMutation
}

// Where appends a list predicates to the UserFollowingUpdate builder.
func (_u *UserFollowingUpdate) Where(ps ...predicate.UserFollowing) *UserFollowingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeleteAt sets the "delete_at" field.
func (_u *UserFollowingUpdate) SetDeleteAt(v time.Time) *UserFollowingUpdate {
	_u.mutation.SetDeleteAt(v)
	return _u
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (_u *UserFollowingUpdate) SetNillableDeleteAt(v *time.Time) *UserFollowingUpdate {
	if v != nil {
		_u.SetDeleteAt(*v)
	}
	return _u
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (_u *UserFollowingUpdate) ClearDeleteAt() *UserFollowingUpdate {
	_u.mutation.ClearDeleteAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserFollowingUpdate) SetUserID(v int64) *UserFollowingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserFollowingUpdate) SetNillableUserID(v *int64) *UserFollowingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStreamerID sets the "streamer_id" field.
func (_u *UserFollowingUpdate) SetStreamerID(v int64) *UserFollowingUpdate {
	_u.mutation.SetStreamerID(v)
	return _u
}

// SetNillableStreamerID sets the "streamer_id" field if the given value is not nil.
func (_u *UserFollowingUpdate) SetNillableStreamerID(v *int64) *UserFollowingUpdate {
	if v != nil {
		_u.SetStreamerID(*v)
	}
	return _u
}

// SetNotificationEnabled sets the "notification_enabled" field.
func (_u *UserFollowingUpdate) SetNotificationEnabled(v bool) *UserFollowingUpdate {
	_u.mutation.SetNotificationEnabled(v)
	return _u
}

// SetNillableNotificationEnabled sets the "notification_enabled" field if the given value is not nil.
func (_u *UserFollowingUpdate) SetNillableNotificationEnabled(v *bool) *UserFollowingUpdate {
	if v != nil {
		_u.SetNotificationEnabled(*v)
	}
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *UserFollowingUpdate) SetLastNotifiedAt(v time.Time) *UserFollowingUpdate {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *UserFollowingUpdate) SetNillableLastNotifiedAt(v *time.Time) *UserFollowingUpdate {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (_u *UserFollowingUpdate) ClearLastNotifiedAt() *UserFollowingUpdate {
	_u.mutation.ClearLastNotifiedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserFollowingUpdate) SetUpdatedAt(v time.Time) *UserFollowingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserFollowingUpdate) SetUser(v *User) *UserFollowingUpdate {
	return _u.SetUserID(v.ID)
}

// SetStreamer sets the "streamer" edge to the Streamer entity.
func (_u *UserFollowingUpdate) SetStreamer(v *Streamer) *UserFollowingUpdate {
	return _u.SetStreamerID(v.ID)
}

// Mutation returns the UserFollowingMutation object of the builder.
func (_u *UserFollowingUpdate) Mutation() *UserFollowingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserFollowingUpdate) ClearUser() *UserFollowingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearStreamer clears the "streamer" edge to the Streamer entity.
func (_u *UserFollowingUpdate) ClearStreamer() *UserFollowingUpdate {
	_u.mutation.ClearStreamer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserFollowingUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserFollowingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserFollowingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserFollowingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserFollowingUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userfollowing.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userfollowing.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userfollowing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserFollowingUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := userfollowing.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowing.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamerID(); ok {
		if err := userfollowing.StreamerIDValidator(v); err != nil {
			return &ValidationError{Name: "streamer_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowing.streamer_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserFollowing.user"`)
	}
	if _u.mutation.StreamerCleared() && len(_u.mutation.StreamerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserFollowing.streamer"`)
	}
	return nil
}

func (_u *UserFollowingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userfollowing.Table, userfollowing.Columns, sqlgraph.NewFieldSpec(userfollowing.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeleteAt(); ok {
		_spec.SetField(userfollowing.FieldDeleteAt, field.TypeTime, value)
	}
	if _u.mutation.DeleteAtCleared() {
		_spec.ClearField(userfollowing.FieldDeleteAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotificationEnabled(); ok {
		_spec.SetField(userfollowing.FieldNotificationEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(userfollowing.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(userfollowing.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userfollowing.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.UserTable,
			Columns: []string{userfollowing.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.UserTable,
			Columns: []string{userfollowing.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StreamerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.StreamerTable,
			Columns: []string{userfollowing.StreamerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StreamerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.StreamerTable,
			Columns: []string{userfollowing.StreamerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userfollowing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserFollowingUpdateOne is the builder for updating a single UserFollowing entity.
type UserFollowingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserFollowingMutation
}

// SetDeleteAt sets the "delete_at" field.
func (_u *UserFollowingUpdateOne) SetDeleteAt(v time.Time) *UserFollowingUpdateOne {
	_u.mutation.SetDeleteAt(v)
	return _u
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (_u *UserFollowingUpdateOne) SetNillableDeleteAt(v *time.Time) *UserFollowingUpdateOne {
	if v != nil {
		_u.SetDeleteAt(*v)
	}
	return _u
}

// ClearDeleteAt clears the value of the "delete_at" field.
func (_u *UserFollowingUpdateOne) ClearDeleteAt() *UserFollowingUpdateOne {
	_u.mutation.ClearDeleteAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserFollowingUpdateOne) SetUserID(v int64) *UserFollowingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserFollowingUpdateOne) SetNillableUserID(v *int64) *UserFollowingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStreamerID sets the "streamer_id" field.
func (_u *UserFollowingUpdateOne) SetStreamerID(v int64) *UserFollowingUpdateOne {
	_u.mutation.SetStreamerID(v)
	return _u
}

// SetNillableStreamerID sets the "streamer_id" field if the given value is not nil.
func (_u *UserFollowingUpdateOne) SetNillableStreamerID(v *int64) *UserFollowingUpdateOne {
	if v != nil {
		_u.SetStreamerID(*v)
	}
	return _u
}

// SetNotificationEnabled sets the "notification_enabled" field.
func (_u *UserFollowingUpdateOne) SetNotificationEnabled(v bool) *UserFollowingUpdateOne {
	_u.mutation.SetNotificationEnabled(v)
	return _u
}

// SetNillableNotificationEnabled sets the "notification_enabled" field if the given value is not nil.
func (_u *UserFollowingUpdateOne) SetNillableNotificationEnabled(v *bool) *UserFollowingUpdateOne {
	if v != nil {
		_u.SetNotificationEnabled(*v)
	}
	return _u
}

// SetLastNotifiedAt sets the "last_notified_at" field.
func (_u *UserFollowingUpdateOne) SetLastNotifiedAt(v time.Time) *UserFollowingUpdateOne {
	_u.mutation.SetLastNotifiedAt(v)
	return _u
}

// SetNillableLastNotifiedAt sets the "last_notified_at" field if the given value is not nil.
func (_u *UserFollowingUpdateOne) SetNillableLastNotifiedAt(v *time.Time) *UserFollowingUpdateOne {
	if v != nil {
		_u.SetLastNotifiedAt(*v)
	}
	return _u
}

// ClearLastNotifiedAt clears the value of the "last_notified_at" field.
func (_u *UserFollowingUpdateOne) ClearLastNotifiedAt() *UserFollowingUpdateOne {
	_u.mutation.ClearLastNotifiedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserFollowingUpdateOne) SetUpdatedAt(v time.Time) *UserFollowingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserFollowingUpdateOne) SetUser(v *User) *UserFollowingUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetStreamer sets the "streamer" edge to the Streamer entity.
func (_u *UserFollowingUpdateOne) SetStreamer(v *Streamer) *UserFollowingUpdateOne {
	return _u.SetStreamerID(v.ID)
}

// Mutation returns the UserFollowingMutation object of the builder.
func (_u *UserFollowingUpdateOne) Mutation() *UserFollowingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserFollowingUpdateOne) ClearUser() *UserFollowingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearStreamer clears the "streamer" edge to the Streamer entity.
func (_u *UserFollowingUpdateOne) ClearStreamer() *UserFollowingUpdateOne {
	_u.mutation.ClearStreamer()
	return _u
}

// Where appends a list predicates to the UserFollowingUpdate builder.
func (_u *UserFollowingUpdateOne) Where(ps ...predicate.UserFollowing) *UserFollowingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserFollowingUpdateOne) Select(field string, fields ...string) *UserFollowingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserFollowing entity.
func (_u *UserFollowingUpdateOne) Save(ctx context.Context) (*UserFollowing, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserFollowingUpdateOne) SaveX(ctx context.Context) *UserFollowing {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserFollowingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserFollowingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserFollowingUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if userfollowing.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized userfollowing.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := userfollowing.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserFollowingUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := userfollowing.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowing.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StreamerID(); ok {
		if err := userfollowing.StreamerIDValidator(v); err != nil {
			return &ValidationError{Name: "streamer_id", err: fmt.Errorf(`ent: validator failed for field "UserFollowing.streamer_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserFollowing.user"`)
	}
	if _u.mutation.StreamerCleared() && len(_u.mutation.StreamerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserFollowing.streamer"`)
	}
	return nil
}

func (_u *UserFollowingUpdateOne) sqlSave(ctx context.Context) (_node *UserFollowing, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userfollowing.Table, userfollowing.Columns, sqlgraph.NewFieldSpec(userfollowing.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserFollowing.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userfollowing.FieldID)
		for _, f := range fields {
			if !userfollowing.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userfollowing.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeleteAt(); ok {
		_spec.SetField(userfollowing.FieldDeleteAt, field.TypeTime, value)
	}
	if _u.mutation.DeleteAtCleared() {
		_spec.ClearField(userfollowing.FieldDeleteAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NotificationEnabled(); ok {
		_spec.SetField(userfollowing.FieldNotificationEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastNotifiedAt(); ok {
		_spec.SetField(userfollowing.FieldLastNotifiedAt, field.TypeTime, value)
	}
	if _u.mutation.LastNotifiedAtCleared() {
		_spec.ClearField(userfollowing.FieldLastNotifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userfollowing.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.UserTable,
			Columns: []string{userfollowing.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.UserTable,
			Columns: []string{userfollowing.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StreamerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.StreamerTable,
			Columns: []string{userfollowing.StreamerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StreamerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userfollowing.StreamerTable,
			Columns: []string{userfollowing.StreamerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(streamer.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserFollowing{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userfollowing.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
