basePath: /api/v1
definitions:
  request.CreateUserRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
      repeat_password:
        type: string
      status:
        enum:
        - active
        - inactive
        - banned
        type: string
      username:
        maxLength: 16
        minLength: 3
        type: string
    required:
    - email
    - password
    - repeat_password
    - status
    - username
    type: object
  request.UpdateUserRequest:
    properties:
      email:
        type: string
      id:
        minimum: 1
        type: integer
      password:
        maxLength: 32
        minLength: 6
        type: string
      repeat_password:
        type: string
      status:
        enum:
        - active
        - inactive
        - banned
        type: string
      username:
        maxLength: 16
        minLength: 3
        type: string
    required:
    - email
    - id
    - password
    - repeat_password
    - status
    - username
    type: object
  response.PaginationResponse-response_UserResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/response.UserResponse'
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
      total_pages:
        type: integer
    type: object
  response.UserResponse:
    properties:
      created_at:
        type: string
      delete_at:
        type: string
      email:
        type: string
      id:
        type: integer
      status:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is an api server for stream build with fiber
  title: Fusion API
  version: "1.0"
paths:
  /user:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
      summary: 创建用户
      tags:
      - User
    put:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
      summary: 更新用户
      tags:
      - User
  /user/{id}:
    delete:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 删除用户
      tags:
      - User
    get:
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
      summary: 获取用户详情
      tags:
      - User
  /user/list:
    get:
      parameters:
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 10
        description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.PaginationResponse-response_UserResponse'
      summary: 获取用户列表
      tags:
      - User
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
