// Code generated by ent, DO NOT EDIT.

package streamer

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the streamer type in the database.
	Label = "streamer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeleteAt holds the string denoting the delete_at field in the database.
	FieldDeleteAt = "delete_at"
	// FieldPlatformID holds the string denoting the platform_id field in the database.
	FieldPlatformID = "platform_id"
	// FieldPlatformStreamerID holds the string denoting the platform_streamer_id field in the database.
	FieldPlatformStreamerID = "platform_streamer_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldRoomURL holds the string denoting the room_url field in the database.
	FieldRoomURL = "room_url"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldIsLive holds the string denoting the is_live field in the database.
	FieldIsLive = "is_live"
	// FieldLastLiveAt holds the string denoting the last_live_at field in the database.
	FieldLastLiveAt = "last_live_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePlatform holds the string denoting the platform edge name in mutations.
	EdgePlatform = "platform"
	// EdgeFollowings holds the string denoting the followings edge name in mutations.
	EdgeFollowings = "followings"
	// Table holds the table name of the streamer in the database.
	Table = "streamers"
	// PlatformTable is the table that holds the platform relation/edge.
	PlatformTable = "streamers"
	// PlatformInverseTable is the table name for the Platform entity.
	// It exists in this package in order to avoid circular dependency with the "platform" package.
	PlatformInverseTable = "platforms"
	// PlatformColumn is the table column denoting the platform relation/edge.
	PlatformColumn = "platform_id"
	// FollowingsTable is the table that holds the followings relation/edge.
	FollowingsTable = "user_followings"
	// FollowingsInverseTable is the table name for the UserFollowing entity.
	// It exists in this package in order to avoid circular dependency with the "userfollowing" package.
	FollowingsInverseTable = "user_followings"
	// FollowingsColumn is the table column denoting the followings relation/edge.
	FollowingsColumn = "streamer_id"
)

// Columns holds all SQL columns for streamer fields.
var Columns = []string{
	FieldID,
	FieldDeleteAt,
	FieldPlatformID,
	FieldPlatformStreamerID,
	FieldName,
	FieldAvatar,
	FieldDescription,
	FieldRoomURL,
	FieldLastCheckedAt,
	FieldIsLive,
	FieldLastLiveAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/ryuyb/fusion/internal/infrastructure/database/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// PlatformIDValidator is a validator for the "platform_id" field. It is called by the builders before save.
	PlatformIDValidator func(int64) error
	// PlatformStreamerIDValidator is a validator for the "platform_streamer_id" field. It is called by the builders before save.
	PlatformStreamerIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsLive holds the default value on creation for the "is_live" field.
	DefaultIsLive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Streamer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeleteAt orders the results by the delete_at field.
func ByDeleteAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteAt, opts...).ToFunc()
}

// ByPlatformID orders the results by the platform_id field.
func ByPlatformID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformID, opts...).ToFunc()
}

// ByPlatformStreamerID orders the results by the platform_streamer_id field.
func ByPlatformStreamerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformStreamerID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAvatar orders the results by the avatar field.
func ByAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatar, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByRoomURL orders the results by the room_url field.
func ByRoomURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoomURL, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByIsLive orders the results by the is_live field.
func ByIsLive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLive, opts...).ToFunc()
}

// ByLastLiveAt orders the results by the last_live_at field.
func ByLastLiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLiveAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPlatformField orders the results by platform field.
func ByPlatformField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlatformStep(), sql.OrderByField(field, opts...))
	}
}

// ByFollowingsCount orders the results by followings count.
func ByFollowingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFollowingsStep(), opts...)
	}
}

// ByFollowings orders the results by followings terms.
func ByFollowings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFollowingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlatformStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlatformInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlatformTable, PlatformColumn),
	)
}
func newFollowingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FollowingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FollowingsTable, FollowingsColumn),
	)
}
