// Code generated by ent, DO NOT EDIT.

package streamer

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/ryuyb/fusion/internal/infrastructure/database/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldID, id))
}

// PlatformType applies equality check predicate on the "platform_type" field. It's identical to PlatformTypeEQ.
func PlatformType(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldPlatformType, v))
}

// PlatformStreamerID applies equality check predicate on the "platform_streamer_id" field. It's identical to PlatformStreamerIDEQ.
func PlatformStreamerID(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldPlatformStreamerID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldDisplayName, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldAvatarURL, v))
}

// RoomURL applies equality check predicate on the "room_url" field. It's identical to RoomURLEQ.
func RoomURL(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldRoomURL, v))
}

// Bio applies equality check predicate on the "bio" field. It's identical to BioEQ.
func Bio(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldBio, v))
}

// IsLive applies equality check predicate on the "is_live" field. It's identical to IsLiveEQ.
func IsLive(v bool) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldIsLive, v))
}

// LiveTitle applies equality check predicate on the "live_title" field. It's identical to LiveTitleEQ.
func LiveTitle(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveTitle, v))
}

// LiveGameName applies equality check predicate on the "live_game_name" field. It's identical to LiveGameNameEQ.
func LiveGameName(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveGameName, v))
}

// LiveStartTime applies equality check predicate on the "live_start_time" field. It's identical to LiveStartTimeEQ.
func LiveStartTime(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveStartTime, v))
}

// LiveViewers applies equality check predicate on the "live_viewers" field. It's identical to LiveViewersEQ.
func LiveViewers(v int) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveViewers, v))
}

// LiveCoverImage applies equality check predicate on the "live_cover_image" field. It's identical to LiveCoverImageEQ.
func LiveCoverImage(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveCoverImage, v))
}

// LastLiveSyncedAt applies equality check predicate on the "last_live_synced_at" field. It's identical to LastLiveSyncedAtEQ.
func LastLiveSyncedAt(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLastLiveSyncedAt, v))
}

// LastSyncedAt applies equality check predicate on the "last_synced_at" field. It's identical to LastSyncedAtEQ.
func LastSyncedAt(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLastSyncedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlatformTypeEQ applies the EQ predicate on the "platform_type" field.
func PlatformTypeEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldPlatformType, v))
}

// PlatformTypeNEQ applies the NEQ predicate on the "platform_type" field.
func PlatformTypeNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldPlatformType, v))
}

// PlatformTypeIn applies the In predicate on the "platform_type" field.
func PlatformTypeIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldPlatformType, vs...))
}

// PlatformTypeNotIn applies the NotIn predicate on the "platform_type" field.
func PlatformTypeNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldPlatformType, vs...))
}

// PlatformTypeGT applies the GT predicate on the "platform_type" field.
func PlatformTypeGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldPlatformType, v))
}

// PlatformTypeGTE applies the GTE predicate on the "platform_type" field.
func PlatformTypeGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldPlatformType, v))
}

// PlatformTypeLT applies the LT predicate on the "platform_type" field.
func PlatformTypeLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldPlatformType, v))
}

// PlatformTypeLTE applies the LTE predicate on the "platform_type" field.
func PlatformTypeLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldPlatformType, v))
}

// PlatformTypeContains applies the Contains predicate on the "platform_type" field.
func PlatformTypeContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldPlatformType, v))
}

// PlatformTypeHasPrefix applies the HasPrefix predicate on the "platform_type" field.
func PlatformTypeHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldPlatformType, v))
}

// PlatformTypeHasSuffix applies the HasSuffix predicate on the "platform_type" field.
func PlatformTypeHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldPlatformType, v))
}

// PlatformTypeEqualFold applies the EqualFold predicate on the "platform_type" field.
func PlatformTypeEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldPlatformType, v))
}

// PlatformTypeContainsFold applies the ContainsFold predicate on the "platform_type" field.
func PlatformTypeContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldPlatformType, v))
}

// PlatformStreamerIDEQ applies the EQ predicate on the "platform_streamer_id" field.
func PlatformStreamerIDEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDNEQ applies the NEQ predicate on the "platform_streamer_id" field.
func PlatformStreamerIDNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDIn applies the In predicate on the "platform_streamer_id" field.
func PlatformStreamerIDIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldPlatformStreamerID, vs...))
}

// PlatformStreamerIDNotIn applies the NotIn predicate on the "platform_streamer_id" field.
func PlatformStreamerIDNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldPlatformStreamerID, vs...))
}

// PlatformStreamerIDGT applies the GT predicate on the "platform_streamer_id" field.
func PlatformStreamerIDGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDGTE applies the GTE predicate on the "platform_streamer_id" field.
func PlatformStreamerIDGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDLT applies the LT predicate on the "platform_streamer_id" field.
func PlatformStreamerIDLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDLTE applies the LTE predicate on the "platform_streamer_id" field.
func PlatformStreamerIDLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDContains applies the Contains predicate on the "platform_streamer_id" field.
func PlatformStreamerIDContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDHasPrefix applies the HasPrefix predicate on the "platform_streamer_id" field.
func PlatformStreamerIDHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDHasSuffix applies the HasSuffix predicate on the "platform_streamer_id" field.
func PlatformStreamerIDHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDEqualFold applies the EqualFold predicate on the "platform_streamer_id" field.
func PlatformStreamerIDEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldPlatformStreamerID, v))
}

// PlatformStreamerIDContainsFold applies the ContainsFold predicate on the "platform_streamer_id" field.
func PlatformStreamerIDContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldPlatformStreamerID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldDisplayName, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldAvatarURL, v))
}

// RoomURLEQ applies the EQ predicate on the "room_url" field.
func RoomURLEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldRoomURL, v))
}

// RoomURLNEQ applies the NEQ predicate on the "room_url" field.
func RoomURLNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldRoomURL, v))
}

// RoomURLIn applies the In predicate on the "room_url" field.
func RoomURLIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldRoomURL, vs...))
}

// RoomURLNotIn applies the NotIn predicate on the "room_url" field.
func RoomURLNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldRoomURL, vs...))
}

// RoomURLGT applies the GT predicate on the "room_url" field.
func RoomURLGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldRoomURL, v))
}

// RoomURLGTE applies the GTE predicate on the "room_url" field.
func RoomURLGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldRoomURL, v))
}

// RoomURLLT applies the LT predicate on the "room_url" field.
func RoomURLLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldRoomURL, v))
}

// RoomURLLTE applies the LTE predicate on the "room_url" field.
func RoomURLLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldRoomURL, v))
}

// RoomURLContains applies the Contains predicate on the "room_url" field.
func RoomURLContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldRoomURL, v))
}

// RoomURLHasPrefix applies the HasPrefix predicate on the "room_url" field.
func RoomURLHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldRoomURL, v))
}

// RoomURLHasSuffix applies the HasSuffix predicate on the "room_url" field.
func RoomURLHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldRoomURL, v))
}

// RoomURLIsNil applies the IsNil predicate on the "room_url" field.
func RoomURLIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldRoomURL))
}

// RoomURLNotNil applies the NotNil predicate on the "room_url" field.
func RoomURLNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldRoomURL))
}

// RoomURLEqualFold applies the EqualFold predicate on the "room_url" field.
func RoomURLEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldRoomURL, v))
}

// RoomURLContainsFold applies the ContainsFold predicate on the "room_url" field.
func RoomURLContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldRoomURL, v))
}

// BioEQ applies the EQ predicate on the "bio" field.
func BioEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldBio, v))
}

// BioNEQ applies the NEQ predicate on the "bio" field.
func BioNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldBio, v))
}

// BioIn applies the In predicate on the "bio" field.
func BioIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldBio, vs...))
}

// BioNotIn applies the NotIn predicate on the "bio" field.
func BioNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldBio, vs...))
}

// BioGT applies the GT predicate on the "bio" field.
func BioGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldBio, v))
}

// BioGTE applies the GTE predicate on the "bio" field.
func BioGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldBio, v))
}

// BioLT applies the LT predicate on the "bio" field.
func BioLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldBio, v))
}

// BioLTE applies the LTE predicate on the "bio" field.
func BioLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldBio, v))
}

// BioContains applies the Contains predicate on the "bio" field.
func BioContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldBio, v))
}

// BioHasPrefix applies the HasPrefix predicate on the "bio" field.
func BioHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldBio, v))
}

// BioHasSuffix applies the HasSuffix predicate on the "bio" field.
func BioHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldBio, v))
}

// BioIsNil applies the IsNil predicate on the "bio" field.
func BioIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldBio))
}

// BioNotNil applies the NotNil predicate on the "bio" field.
func BioNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldBio))
}

// BioEqualFold applies the EqualFold predicate on the "bio" field.
func BioEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldBio, v))
}

// BioContainsFold applies the ContainsFold predicate on the "bio" field.
func BioContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldBio, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldTags))
}

// IsLiveEQ applies the EQ predicate on the "is_live" field.
func IsLiveEQ(v bool) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldIsLive, v))
}

// IsLiveNEQ applies the NEQ predicate on the "is_live" field.
func IsLiveNEQ(v bool) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldIsLive, v))
}

// LiveTitleEQ applies the EQ predicate on the "live_title" field.
func LiveTitleEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveTitle, v))
}

// LiveTitleNEQ applies the NEQ predicate on the "live_title" field.
func LiveTitleNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldLiveTitle, v))
}

// LiveTitleIn applies the In predicate on the "live_title" field.
func LiveTitleIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldLiveTitle, vs...))
}

// LiveTitleNotIn applies the NotIn predicate on the "live_title" field.
func LiveTitleNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldLiveTitle, vs...))
}

// LiveTitleGT applies the GT predicate on the "live_title" field.
func LiveTitleGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldLiveTitle, v))
}

// LiveTitleGTE applies the GTE predicate on the "live_title" field.
func LiveTitleGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldLiveTitle, v))
}

// LiveTitleLT applies the LT predicate on the "live_title" field.
func LiveTitleLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldLiveTitle, v))
}

// LiveTitleLTE applies the LTE predicate on the "live_title" field.
func LiveTitleLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldLiveTitle, v))
}

// LiveTitleContains applies the Contains predicate on the "live_title" field.
func LiveTitleContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldLiveTitle, v))
}

// LiveTitleHasPrefix applies the HasPrefix predicate on the "live_title" field.
func LiveTitleHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldLiveTitle, v))
}

// LiveTitleHasSuffix applies the HasSuffix predicate on the "live_title" field.
func LiveTitleHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldLiveTitle, v))
}

// LiveTitleIsNil applies the IsNil predicate on the "live_title" field.
func LiveTitleIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldLiveTitle))
}

// LiveTitleNotNil applies the NotNil predicate on the "live_title" field.
func LiveTitleNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldLiveTitle))
}

// LiveTitleEqualFold applies the EqualFold predicate on the "live_title" field.
func LiveTitleEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldLiveTitle, v))
}

// LiveTitleContainsFold applies the ContainsFold predicate on the "live_title" field.
func LiveTitleContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldLiveTitle, v))
}

// LiveGameNameEQ applies the EQ predicate on the "live_game_name" field.
func LiveGameNameEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveGameName, v))
}

// LiveGameNameNEQ applies the NEQ predicate on the "live_game_name" field.
func LiveGameNameNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldLiveGameName, v))
}

// LiveGameNameIn applies the In predicate on the "live_game_name" field.
func LiveGameNameIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldLiveGameName, vs...))
}

// LiveGameNameNotIn applies the NotIn predicate on the "live_game_name" field.
func LiveGameNameNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldLiveGameName, vs...))
}

// LiveGameNameGT applies the GT predicate on the "live_game_name" field.
func LiveGameNameGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldLiveGameName, v))
}

// LiveGameNameGTE applies the GTE predicate on the "live_game_name" field.
func LiveGameNameGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldLiveGameName, v))
}

// LiveGameNameLT applies the LT predicate on the "live_game_name" field.
func LiveGameNameLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldLiveGameName, v))
}

// LiveGameNameLTE applies the LTE predicate on the "live_game_name" field.
func LiveGameNameLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldLiveGameName, v))
}

// LiveGameNameContains applies the Contains predicate on the "live_game_name" field.
func LiveGameNameContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldLiveGameName, v))
}

// LiveGameNameHasPrefix applies the HasPrefix predicate on the "live_game_name" field.
func LiveGameNameHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldLiveGameName, v))
}

// LiveGameNameHasSuffix applies the HasSuffix predicate on the "live_game_name" field.
func LiveGameNameHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldLiveGameName, v))
}

// LiveGameNameIsNil applies the IsNil predicate on the "live_game_name" field.
func LiveGameNameIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldLiveGameName))
}

// LiveGameNameNotNil applies the NotNil predicate on the "live_game_name" field.
func LiveGameNameNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldLiveGameName))
}

// LiveGameNameEqualFold applies the EqualFold predicate on the "live_game_name" field.
func LiveGameNameEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldLiveGameName, v))
}

// LiveGameNameContainsFold applies the ContainsFold predicate on the "live_game_name" field.
func LiveGameNameContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldLiveGameName, v))
}

// LiveStartTimeEQ applies the EQ predicate on the "live_start_time" field.
func LiveStartTimeEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveStartTime, v))
}

// LiveStartTimeNEQ applies the NEQ predicate on the "live_start_time" field.
func LiveStartTimeNEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldLiveStartTime, v))
}

// LiveStartTimeIn applies the In predicate on the "live_start_time" field.
func LiveStartTimeIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldLiveStartTime, vs...))
}

// LiveStartTimeNotIn applies the NotIn predicate on the "live_start_time" field.
func LiveStartTimeNotIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldLiveStartTime, vs...))
}

// LiveStartTimeGT applies the GT predicate on the "live_start_time" field.
func LiveStartTimeGT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldLiveStartTime, v))
}

// LiveStartTimeGTE applies the GTE predicate on the "live_start_time" field.
func LiveStartTimeGTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldLiveStartTime, v))
}

// LiveStartTimeLT applies the LT predicate on the "live_start_time" field.
func LiveStartTimeLT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldLiveStartTime, v))
}

// LiveStartTimeLTE applies the LTE predicate on the "live_start_time" field.
func LiveStartTimeLTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldLiveStartTime, v))
}

// LiveStartTimeIsNil applies the IsNil predicate on the "live_start_time" field.
func LiveStartTimeIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldLiveStartTime))
}

// LiveStartTimeNotNil applies the NotNil predicate on the "live_start_time" field.
func LiveStartTimeNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldLiveStartTime))
}

// LiveViewersEQ applies the EQ predicate on the "live_viewers" field.
func LiveViewersEQ(v int) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveViewers, v))
}

// LiveViewersNEQ applies the NEQ predicate on the "live_viewers" field.
func LiveViewersNEQ(v int) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldLiveViewers, v))
}

// LiveViewersIn applies the In predicate on the "live_viewers" field.
func LiveViewersIn(vs ...int) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldLiveViewers, vs...))
}

// LiveViewersNotIn applies the NotIn predicate on the "live_viewers" field.
func LiveViewersNotIn(vs ...int) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldLiveViewers, vs...))
}

// LiveViewersGT applies the GT predicate on the "live_viewers" field.
func LiveViewersGT(v int) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldLiveViewers, v))
}

// LiveViewersGTE applies the GTE predicate on the "live_viewers" field.
func LiveViewersGTE(v int) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldLiveViewers, v))
}

// LiveViewersLT applies the LT predicate on the "live_viewers" field.
func LiveViewersLT(v int) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldLiveViewers, v))
}

// LiveViewersLTE applies the LTE predicate on the "live_viewers" field.
func LiveViewersLTE(v int) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldLiveViewers, v))
}

// LiveViewersIsNil applies the IsNil predicate on the "live_viewers" field.
func LiveViewersIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldLiveViewers))
}

// LiveViewersNotNil applies the NotNil predicate on the "live_viewers" field.
func LiveViewersNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldLiveViewers))
}

// LiveCoverImageEQ applies the EQ predicate on the "live_cover_image" field.
func LiveCoverImageEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLiveCoverImage, v))
}

// LiveCoverImageNEQ applies the NEQ predicate on the "live_cover_image" field.
func LiveCoverImageNEQ(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldLiveCoverImage, v))
}

// LiveCoverImageIn applies the In predicate on the "live_cover_image" field.
func LiveCoverImageIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldLiveCoverImage, vs...))
}

// LiveCoverImageNotIn applies the NotIn predicate on the "live_cover_image" field.
func LiveCoverImageNotIn(vs ...string) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldLiveCoverImage, vs...))
}

// LiveCoverImageGT applies the GT predicate on the "live_cover_image" field.
func LiveCoverImageGT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldLiveCoverImage, v))
}

// LiveCoverImageGTE applies the GTE predicate on the "live_cover_image" field.
func LiveCoverImageGTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldLiveCoverImage, v))
}

// LiveCoverImageLT applies the LT predicate on the "live_cover_image" field.
func LiveCoverImageLT(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldLiveCoverImage, v))
}

// LiveCoverImageLTE applies the LTE predicate on the "live_cover_image" field.
func LiveCoverImageLTE(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldLiveCoverImage, v))
}

// LiveCoverImageContains applies the Contains predicate on the "live_cover_image" field.
func LiveCoverImageContains(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContains(FieldLiveCoverImage, v))
}

// LiveCoverImageHasPrefix applies the HasPrefix predicate on the "live_cover_image" field.
func LiveCoverImageHasPrefix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasPrefix(FieldLiveCoverImage, v))
}

// LiveCoverImageHasSuffix applies the HasSuffix predicate on the "live_cover_image" field.
func LiveCoverImageHasSuffix(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldHasSuffix(FieldLiveCoverImage, v))
}

// LiveCoverImageIsNil applies the IsNil predicate on the "live_cover_image" field.
func LiveCoverImageIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldLiveCoverImage))
}

// LiveCoverImageNotNil applies the NotNil predicate on the "live_cover_image" field.
func LiveCoverImageNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldLiveCoverImage))
}

// LiveCoverImageEqualFold applies the EqualFold predicate on the "live_cover_image" field.
func LiveCoverImageEqualFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldEqualFold(FieldLiveCoverImage, v))
}

// LiveCoverImageContainsFold applies the ContainsFold predicate on the "live_cover_image" field.
func LiveCoverImageContainsFold(v string) predicate.Streamer {
	return predicate.Streamer(sql.FieldContainsFold(FieldLiveCoverImage, v))
}

// LastLiveSyncedAtEQ applies the EQ predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLastLiveSyncedAt, v))
}

// LastLiveSyncedAtNEQ applies the NEQ predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtNEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldLastLiveSyncedAt, v))
}

// LastLiveSyncedAtIn applies the In predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldLastLiveSyncedAt, vs...))
}

// LastLiveSyncedAtNotIn applies the NotIn predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtNotIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldLastLiveSyncedAt, vs...))
}

// LastLiveSyncedAtGT applies the GT predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtGT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldLastLiveSyncedAt, v))
}

// LastLiveSyncedAtGTE applies the GTE predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtGTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldLastLiveSyncedAt, v))
}

// LastLiveSyncedAtLT applies the LT predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtLT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldLastLiveSyncedAt, v))
}

// LastLiveSyncedAtLTE applies the LTE predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtLTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldLastLiveSyncedAt, v))
}

// LastLiveSyncedAtIsNil applies the IsNil predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldLastLiveSyncedAt))
}

// LastLiveSyncedAtNotNil applies the NotNil predicate on the "last_live_synced_at" field.
func LastLiveSyncedAtNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldLastLiveSyncedAt))
}

// LastSyncedAtEQ applies the EQ predicate on the "last_synced_at" field.
func LastSyncedAtEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtNEQ applies the NEQ predicate on the "last_synced_at" field.
func LastSyncedAtNEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldLastSyncedAt, v))
}

// LastSyncedAtIn applies the In predicate on the "last_synced_at" field.
func LastSyncedAtIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtNotIn applies the NotIn predicate on the "last_synced_at" field.
func LastSyncedAtNotIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldLastSyncedAt, vs...))
}

// LastSyncedAtGT applies the GT predicate on the "last_synced_at" field.
func LastSyncedAtGT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldLastSyncedAt, v))
}

// LastSyncedAtGTE applies the GTE predicate on the "last_synced_at" field.
func LastSyncedAtGTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldLastSyncedAt, v))
}

// LastSyncedAtLT applies the LT predicate on the "last_synced_at" field.
func LastSyncedAtLT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldLastSyncedAt, v))
}

// LastSyncedAtLTE applies the LTE predicate on the "last_synced_at" field.
func LastSyncedAtLTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldLastSyncedAt, v))
}

// LastSyncedAtIsNil applies the IsNil predicate on the "last_synced_at" field.
func LastSyncedAtIsNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldIsNull(FieldLastSyncedAt))
}

// LastSyncedAtNotNil applies the NotNil predicate on the "last_synced_at" field.
func LastSyncedAtNotNil() predicate.Streamer {
	return predicate.Streamer(sql.FieldNotNull(FieldLastSyncedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Streamer {
	return predicate.Streamer(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasFollowers applies the HasEdge predicate on the "followers" edge.
func HasFollowers() predicate.Streamer {
	return predicate.Streamer(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, FollowersTable, FollowersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFollowersWith applies the HasEdge predicate on the "followers" edge with a given conditions (other predicates).
func HasFollowersWith(preds ...predicate.UserFollowedStreamer) predicate.Streamer {
	return predicate.Streamer(func(s *sql.Selector) {
		step := newFollowersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Streamer) predicate.Streamer {
	return predicate.Streamer(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Streamer) predicate.Streamer {
	return predicate.Streamer(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Streamer) predicate.Streamer {
	return predicate.Streamer(sql.NotPredicates(p))
}
